version: "3.8"
services:
  web:
    container_name: Dfe.ManageFreeSchoolProjects.Web
    build:
      context: .
      dockerfile: Dockerfile.web
    command: /bin/bash -c "./docker-entrypoint.sh dotnet Dfe.ManageFreeSchoolProjects.dll"
    ports:
      - 80:80/tcp
    depends_on:
      - api
    env_file:
       - .env.development.local
    networks:
      - dev

  api:
    container_name: Dfe.ManageFreeSchoolProjects.API
    build:
      context: .
      dockerfile: Dockerfile.api
    command: /bin/bash -c "./docker-entrypoint.sh dotnet Dfe.ManageFreeSchoolProjects.API.dll"
    ports:
      - 88:80/tcp
    depends_on:
      - db
      - sqlcmd
    env_file:
       - .env.development.local
    networks:
      - dev

  db:
    container_name: Dfe.ManageFreeSchoolProjects.SQL
    image: mcr.microsoft.com/azure-sql-edge:latest@sha256:902628a8be89e35dfb7895ca31d602974c7bafde4d583a0d0873844feb1c42cf
    env_file: .env.database
    ports:
      - 1433:1433
    networks:
      - dev

  sqlcmd:
    container_name: Dfe.ManageFreeSchoolProjects.Tools
    image: mcr.microsoft.com/mssql-tools:latest@sha256:62556500522072535cb3df2bb5965333dded9be47000473e9e0f84118e248642
    env_file: .env.database
    command: /etc/docker-entrypoint.sh
    depends_on:
      - db
    stdin_open: true
    volumes:
      - ./script/sqlcmd-docker-entrypoint.sh:/etc/docker-entrypoint.sh
    networks:
      - dev

networks:
  dev:
