// <auto-generated />
using System;
using System.Reflection;
using Dfe.ManageFreeSchoolProjects.Data.Entities.Existing;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Dfe.ManageFreeSchoolProjects.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class BasicNeedEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Dfe.ManageFreeSchoolProjects.Data.Entities.Existing.BasicNeed",
                typeof(BasicNeed),
                baseEntityType,
                propertyCount: 16);

            var freeSchoolName = runtimeEntityType.AddProperty(
                "FreeSchoolName",
                typeof(string),
                propertyInfo: typeof(BasicNeed).GetProperty("FreeSchoolName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BasicNeed).GetField("<FreeSchoolName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            freeSchoolName.AddAnnotation("Relational:ColumnName", "Free school name");
            freeSchoolName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var phase = runtimeEntityType.AddProperty(
                "Phase",
                typeof(string),
                propertyInfo: typeof(BasicNeed).GetProperty("Phase", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BasicNeed).GetField("<Phase>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            phase.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var postcodeUsedHere = runtimeEntityType.AddProperty(
                "PostcodeUsedHere",
                typeof(string),
                propertyInfo: typeof(BasicNeed).GetProperty("PostcodeUsedHere", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BasicNeed).GetField("<PostcodeUsedHere>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            postcodeUsedHere.AddAnnotation("Relational:ColumnName", "Postcode used here");
            postcodeUsedHere.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var primaryPlanningAreaCode = runtimeEntityType.AddProperty(
                "PrimaryPlanningAreaCode",
                typeof(string),
                propertyInfo: typeof(BasicNeed).GetProperty("PrimaryPlanningAreaCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BasicNeed).GetField("<PrimaryPlanningAreaCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            primaryPlanningAreaCode.AddAnnotation("Relational:ColumnName", "Primary planning area code");
            primaryPlanningAreaCode.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var primaryPlanningAreaName = runtimeEntityType.AddProperty(
                "PrimaryPlanningAreaName",
                typeof(string),
                propertyInfo: typeof(BasicNeed).GetProperty("PrimaryPlanningAreaName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BasicNeed).GetField("<PrimaryPlanningAreaName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            primaryPlanningAreaName.AddAnnotation("Relational:ColumnName", "Primary planning area name");
            primaryPlanningAreaName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var projectId = runtimeEntityType.AddProperty(
                "ProjectId",
                typeof(string),
                propertyInfo: typeof(BasicNeed).GetProperty("ProjectId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BasicNeed).GetField("<ProjectId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 25,
                unicode: false);
            projectId.AddAnnotation("Relational:ColumnName", "Project ID");
            projectId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var secondaryPlanningAreaCode = runtimeEntityType.AddProperty(
                "SecondaryPlanningAreaCode",
                typeof(string),
                propertyInfo: typeof(BasicNeed).GetProperty("SecondaryPlanningAreaCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BasicNeed).GetField("<SecondaryPlanningAreaCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            secondaryPlanningAreaCode.AddAnnotation("Relational:ColumnName", "Secondary planning area code");
            secondaryPlanningAreaCode.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var secondaryPlanningAreaName = runtimeEntityType.AddProperty(
                "SecondaryPlanningAreaName",
                typeof(string),
                propertyInfo: typeof(BasicNeed).GetProperty("SecondaryPlanningAreaName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BasicNeed).GetField("<SecondaryPlanningAreaName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            secondaryPlanningAreaName.AddAnnotation("Relational:ColumnName", "Secondary planning area name");
            secondaryPlanningAreaName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var _201920PrimaryPhaseLocalAreaSSNoPlaces = runtimeEntityType.AddProperty(
                "_201920PrimaryPhaseLocalAreaSSNoPlaces",
                typeof(string),
                propertyInfo: typeof(BasicNeed).GetProperty("_201920PrimaryPhaseLocalAreaSSNoPlaces", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BasicNeed).GetField("<_201920PrimaryPhaseLocalAreaSSNoPlaces>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            _201920PrimaryPhaseLocalAreaSSNoPlaces.AddAnnotation("Relational:ColumnName", "2019/20 Primary Phase Local Area S/S No. places");
            _201920PrimaryPhaseLocalAreaSSNoPlaces.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var _201920PrimaryPhaseLocalAreaSSPlaces = runtimeEntityType.AddProperty(
                "_201920PrimaryPhaseLocalAreaSSPlaces",
                typeof(string),
                propertyInfo: typeof(BasicNeed).GetProperty("_201920PrimaryPhaseLocalAreaSSPlaces", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BasicNeed).GetField("<_201920PrimaryPhaseLocalAreaSSPlaces>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            _201920PrimaryPhaseLocalAreaSSPlaces.AddAnnotation("Relational:ColumnName", "2019/20 Primary Phase Local Area S/S % places");
            _201920PrimaryPhaseLocalAreaSSPlaces.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var _201920PrimaryPhasePlanningAreaSSNoPlaces = runtimeEntityType.AddProperty(
                "_201920PrimaryPhasePlanningAreaSSNoPlaces",
                typeof(string),
                propertyInfo: typeof(BasicNeed).GetProperty("_201920PrimaryPhasePlanningAreaSSNoPlaces", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BasicNeed).GetField("<_201920PrimaryPhasePlanningAreaSSNoPlaces>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            _201920PrimaryPhasePlanningAreaSSNoPlaces.AddAnnotation("Relational:ColumnName", "2019/20 Primary Phase Planning Area S/S No. places");
            _201920PrimaryPhasePlanningAreaSSNoPlaces.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var _201920PrimaryPhasePlanningAreaSSPlaces = runtimeEntityType.AddProperty(
                "_201920PrimaryPhasePlanningAreaSSPlaces",
                typeof(string),
                propertyInfo: typeof(BasicNeed).GetProperty("_201920PrimaryPhasePlanningAreaSSPlaces", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BasicNeed).GetField("<_201920PrimaryPhasePlanningAreaSSPlaces>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            _201920PrimaryPhasePlanningAreaSSPlaces.AddAnnotation("Relational:ColumnName", "2019/20 Primary Phase Planning Area S/S % places");
            _201920PrimaryPhasePlanningAreaSSPlaces.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var _201920SecondaryPhaseLocalAreaSSNoPlaces = runtimeEntityType.AddProperty(
                "_201920SecondaryPhaseLocalAreaSSNoPlaces",
                typeof(string),
                propertyInfo: typeof(BasicNeed).GetProperty("_201920SecondaryPhaseLocalAreaSSNoPlaces", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BasicNeed).GetField("<_201920SecondaryPhaseLocalAreaSSNoPlaces>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            _201920SecondaryPhaseLocalAreaSSNoPlaces.AddAnnotation("Relational:ColumnName", "2019/20 Secondary Phase Local Area S/S No. places");
            _201920SecondaryPhaseLocalAreaSSNoPlaces.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var _201920SecondaryPhaseLocalAreaSSPlaces = runtimeEntityType.AddProperty(
                "_201920SecondaryPhaseLocalAreaSSPlaces",
                typeof(string),
                propertyInfo: typeof(BasicNeed).GetProperty("_201920SecondaryPhaseLocalAreaSSPlaces", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BasicNeed).GetField("<_201920SecondaryPhaseLocalAreaSSPlaces>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            _201920SecondaryPhaseLocalAreaSSPlaces.AddAnnotation("Relational:ColumnName", "2019/20 Secondary Phase Local Area S/S % places");
            _201920SecondaryPhaseLocalAreaSSPlaces.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var _201920SecondaryPhasePlanningAreaSSNoPlaces = runtimeEntityType.AddProperty(
                "_201920SecondaryPhasePlanningAreaSSNoPlaces",
                typeof(string),
                propertyInfo: typeof(BasicNeed).GetProperty("_201920SecondaryPhasePlanningAreaSSNoPlaces", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BasicNeed).GetField("<_201920SecondaryPhasePlanningAreaSSNoPlaces>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            _201920SecondaryPhasePlanningAreaSSNoPlaces.AddAnnotation("Relational:ColumnName", "2019/20 Secondary Phase Planning Area S/S No. places");
            _201920SecondaryPhasePlanningAreaSSNoPlaces.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var _201920SecondaryPhasePlanningAreaSSPlaces = runtimeEntityType.AddProperty(
                "_201920SecondaryPhasePlanningAreaSSPlaces",
                typeof(string),
                propertyInfo: typeof(BasicNeed).GetProperty("_201920SecondaryPhasePlanningAreaSSPlaces", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BasicNeed).GetField("<_201920SecondaryPhasePlanningAreaSSPlaces>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            _201920SecondaryPhasePlanningAreaSSPlaces.AddAnnotation("Relational:ColumnName", "2019/20 Secondary Phase Planning Area S/S % places");
            _201920SecondaryPhasePlanningAreaSSPlaces.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "dbo");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Basic_Need");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
