// <auto-generated />
using System;
using System.Reflection;
using Dfe.ManageFreeSchoolProjects.Data.Entities;
using Dfe.ManageFreeSchoolProjects.Data.Entities.Existing;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Dfe.ManageFreeSchoolProjects.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class BsEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Dfe.ManageFreeSchoolProjects.Data.Entities.Existing.Bs",
                typeof(Bs),
                baseEntityType,
                propertyCount: 26,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var rid = runtimeEntityType.AddProperty(
                "Rid",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("Rid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<Rid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 11,
                unicode: false);
            rid.AddAnnotation("Relational:ColumnName", "RID");
            rid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryAcquisitionBudget = runtimeEntityType.AddProperty(
                "BudgetSummaryAcquisitionBudget",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryAcquisitionBudget", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryAcquisitionBudget>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            budgetSummaryAcquisitionBudget.AddAnnotation("Relational:ColumnName", "Budget summary.Acquisition budget");
            budgetSummaryAcquisitionBudget.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryBudgetApprovalDate = runtimeEntityType.AddProperty(
                "BudgetSummaryBudgetApprovalDate",
                typeof(DateTime?),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryBudgetApprovalDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryBudgetApprovalDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            budgetSummaryBudgetApprovalDate.AddAnnotation("Relational:ColumnName", "Budget summary.Budget approval date");
            budgetSummaryBudgetApprovalDate.AddAnnotation("Relational:ColumnType", "date");
            budgetSummaryBudgetApprovalDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryBudgetApprovalProcess = runtimeEntityType.AddProperty(
                "BudgetSummaryBudgetApprovalProcess",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryBudgetApprovalProcess", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryBudgetApprovalProcess>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            budgetSummaryBudgetApprovalProcess.AddAnnotation("Relational:ColumnName", "Budget summary.Budget approval process");
            budgetSummaryBudgetApprovalProcess.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryBudgetStageSummary = runtimeEntityType.AddProperty(
                "BudgetSummaryBudgetStageSummary",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryBudgetStageSummary", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryBudgetStageSummary>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            budgetSummaryBudgetStageSummary.AddAnnotation("Relational:ColumnName", "Budget summary.Budget stage summary");
            budgetSummaryBudgetStageSummary.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryCapitalCostTier = runtimeEntityType.AddProperty(
                "BudgetSummaryCapitalCostTier",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryCapitalCostTier", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryCapitalCostTier>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            budgetSummaryCapitalCostTier.AddAnnotation("Relational:ColumnName", "Budget summary.Capital cost tier");
            budgetSummaryCapitalCostTier.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryConstructionBudget = runtimeEntityType.AddProperty(
                "BudgetSummaryConstructionBudget",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryConstructionBudget", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryConstructionBudget>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            budgetSummaryConstructionBudget.AddAnnotation("Relational:ColumnName", "Budget summary.Construction budget");
            budgetSummaryConstructionBudget.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryCostPlan1Approved = runtimeEntityType.AddProperty(
                "BudgetSummaryCostPlan1Approved",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryCostPlan1Approved", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryCostPlan1Approved>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            budgetSummaryCostPlan1Approved.AddAnnotation("Relational:ColumnName", "Budget summary.Cost Plan 1 approved");
            budgetSummaryCostPlan1Approved.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryCostPlan2Approved = runtimeEntityType.AddProperty(
                "BudgetSummaryCostPlan2Approved",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryCostPlan2Approved", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryCostPlan2Approved>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            budgetSummaryCostPlan2Approved.AddAnnotation("Relational:ColumnName", "Budget summary.Cost Plan 2 approved");
            budgetSummaryCostPlan2Approved.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryCostsAtPracticalCompletionApproved = runtimeEntityType.AddProperty(
                "BudgetSummaryCostsAtPracticalCompletionApproved",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryCostsAtPracticalCompletionApproved", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryCostsAtPracticalCompletionApproved>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            budgetSummaryCostsAtPracticalCompletionApproved.AddAnnotation("Relational:ColumnName", "Budget summary.Costs at practical completion approved");
            budgetSummaryCostsAtPracticalCompletionApproved.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryFfEBudget = runtimeEntityType.AddProperty(
                "BudgetSummaryFfEBudget",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryFfEBudget", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryFfEBudget>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            budgetSummaryFfEBudget.AddAnnotation("Relational:ColumnName", "Budget summary.FF&E budget");
            budgetSummaryFfEBudget.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryFinalAccountsAgreed = runtimeEntityType.AddProperty(
                "BudgetSummaryFinalAccountsAgreed",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryFinalAccountsAgreed", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryFinalAccountsAgreed>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            budgetSummaryFinalAccountsAgreed.AddAnnotation("Relational:ColumnName", "Budget summary.Final accounts agreed");
            budgetSummaryFinalAccountsAgreed.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryIctBudget = runtimeEntityType.AddProperty(
                "BudgetSummaryIctBudget",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryIctBudget", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryIctBudget>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            budgetSummaryIctBudget.AddAnnotation("Relational:ColumnName", "Budget summary.ICT budget");
            budgetSummaryIctBudget.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryIsTheLaMakingAFinancialContributionTowardsThisProject = runtimeEntityType.AddProperty(
                "BudgetSummaryIsTheLaMakingAFinancialContributionTowardsThisProject",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryIsTheLaMakingAFinancialContributionTowardsThisProject", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryIsTheLaMakingAFinancialContributionTowardsThisProject>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            budgetSummaryIsTheLaMakingAFinancialContributionTowardsThisProject.AddAnnotation("Relational:ColumnName", "Budget summary.Is the LA making a financial contribution towards this project?");
            budgetSummaryIsTheLaMakingAFinancialContributionTowardsThisProject.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryLaContributionType = runtimeEntityType.AddProperty(
                "BudgetSummaryLaContributionType",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryLaContributionType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryLaContributionType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 1000,
                unicode: false);
            budgetSummaryLaContributionType.AddAnnotation("Relational:ColumnName", "Budget summary.LA Contribution type");
            budgetSummaryLaContributionType.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryOtherContributionType = runtimeEntityType.AddProperty(
                "BudgetSummaryOtherContributionType",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryOtherContributionType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryOtherContributionType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            budgetSummaryOtherContributionType.AddAnnotation("Relational:ColumnName", "Budget summary.Other contribution type");
            budgetSummaryOtherContributionType.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryPreCarFundingApproved = runtimeEntityType.AddProperty(
                "BudgetSummaryPreCarFundingApproved",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryPreCarFundingApproved", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryPreCarFundingApproved>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            budgetSummaryPreCarFundingApproved.AddAnnotation("Relational:ColumnName", "Budget summary.Pre CAR funding approved");
            budgetSummaryPreCarFundingApproved.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryPreCarFundingRequired = runtimeEntityType.AddProperty(
                "BudgetSummaryPreCarFundingRequired",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryPreCarFundingRequired", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryPreCarFundingRequired>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            budgetSummaryPreCarFundingRequired.AddAnnotation("Relational:ColumnName", "Budget summary.Pre CAR funding required");
            budgetSummaryPreCarFundingRequired.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryStoreBudgetRecordName = runtimeEntityType.AddProperty(
                "BudgetSummaryStoreBudgetRecordName",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryStoreBudgetRecordName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryStoreBudgetRecordName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            budgetSummaryStoreBudgetRecordName.AddAnnotation("Relational:ColumnName", "Budget summary.Store budget record name");
            budgetSummaryStoreBudgetRecordName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryTemporarySiteBudget = runtimeEntityType.AddProperty(
                "BudgetSummaryTemporarySiteBudget",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryTemporarySiteBudget", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryTemporarySiteBudget>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            budgetSummaryTemporarySiteBudget.AddAnnotation("Relational:ColumnName", "Budget summary.Temporary Site budget");
            budgetSummaryTemporarySiteBudget.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryTotalCapitalBudget = runtimeEntityType.AddProperty(
                "BudgetSummaryTotalCapitalBudget",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryTotalCapitalBudget", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryTotalCapitalBudget>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            budgetSummaryTotalCapitalBudget.AddAnnotation("Relational:ColumnName", "Budget summary.Total capital budget");
            budgetSummaryTotalCapitalBudget.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var budgetSummaryTotalRevenue = runtimeEntityType.AddProperty(
                "BudgetSummaryTotalRevenue",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("BudgetSummaryTotalRevenue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<BudgetSummaryTotalRevenue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            budgetSummaryTotalRevenue.AddAnnotation("Relational:ColumnName", "Budget summary.Total Revenue");
            budgetSummaryTotalRevenue.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var pRid = runtimeEntityType.AddProperty(
                "PRid",
                typeof(string),
                propertyInfo: typeof(Bs).GetProperty("PRid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Bs).GetField("<PRid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 11,
                unicode: false);
            pRid.AddAnnotation("Relational:ColumnName", "p_rid");
            pRid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var periodEnd = runtimeEntityType.AddProperty(
                "PeriodEnd",
                typeof(DateTime),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            periodEnd.AddAnnotation("Relational:ColumnName", "PeriodEnd");
            periodEnd.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var periodStart = runtimeEntityType.AddProperty(
                "PeriodStart",
                typeof(DateTime),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            periodStart.AddAnnotation("Relational:ColumnName", "PeriodStart");
            periodStart.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var updatedByUserId = runtimeEntityType.AddProperty(
                "UpdatedByUserId",
                typeof(int?),
                propertyInfo: typeof(IAuditable).GetProperty("UpdatedByUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IAuditable).GetField("<UpdatedByUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            updatedByUserId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { rid });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { updatedByUserId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UpdatedByUserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "dbo");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "BS");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);
            runtimeEntityType.AddAnnotation("SqlServer:IsTemporal", true);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
