// <auto-generated />
using System;
using System.Reflection;
using Dfe.ManageFreeSchoolProjects.Data.Entities.Existing;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Dfe.ManageFreeSchoolProjects.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ConstructionEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Dfe.ManageFreeSchoolProjects.Data.Entities.Existing.Construction",
                typeof(Construction),
                baseEntityType,
                propertyCount: 23,
                keyCount: 1);

            var rid = runtimeEntityType.AddProperty(
                "Rid",
                typeof(string),
                propertyInfo: typeof(Construction).GetProperty("Rid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<Rid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 11,
                unicode: false);
            rid.AddAnnotation("Relational:ColumnName", "RID");
            rid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ictDetailsBroadbandOrdered = runtimeEntityType.AddProperty(
                "IctDetailsBroadbandOrdered",
                typeof(DateTime?),
                propertyInfo: typeof(Construction).GetProperty("IctDetailsBroadbandOrdered", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<IctDetailsBroadbandOrdered>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            ictDetailsBroadbandOrdered.AddAnnotation("Relational:ColumnName", "ICT Details.Broadband ordered");
            ictDetailsBroadbandOrdered.AddAnnotation("Relational:ColumnType", "date");
            ictDetailsBroadbandOrdered.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ictDetailsIctProcurementRouteAgreedWithTrust = runtimeEntityType.AddProperty(
                "IctDetailsIctProcurementRouteAgreedWithTrust",
                typeof(DateTime?),
                propertyInfo: typeof(Construction).GetProperty("IctDetailsIctProcurementRouteAgreedWithTrust", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<IctDetailsIctProcurementRouteAgreedWithTrust>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            ictDetailsIctProcurementRouteAgreedWithTrust.AddAnnotation("Relational:ColumnName", "ICT Details.ICT procurement route agreed with Trust");
            ictDetailsIctProcurementRouteAgreedWithTrust.AddAnnotation("Relational:ColumnType", "date");
            ictDetailsIctProcurementRouteAgreedWithTrust.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var pRid = runtimeEntityType.AddProperty(
                "PRid",
                typeof(string),
                propertyInfo: typeof(Construction).GetProperty("PRid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<PRid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 11,
                unicode: false);
            pRid.AddAnnotation("Relational:ColumnName", "p_rid");
            pRid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var periodEnd = runtimeEntityType.AddProperty(
                "PeriodEnd",
                typeof(DateTime),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            periodEnd.AddAnnotation("Relational:ColumnName", "PeriodEnd");
            periodEnd.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var periodStart = runtimeEntityType.AddProperty(
                "PeriodStart",
                typeof(DateTime),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            periodStart.AddAnnotation("Relational:ColumnName", "PeriodStart");
            periodStart.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var siteDetailsAreaOfExistingBuildingsM2PermanentArea = runtimeEntityType.AddProperty(
                "SiteDetailsAreaOfExistingBuildingsM2PermanentArea",
                typeof(string),
                propertyInfo: typeof(Construction).GetProperty("SiteDetailsAreaOfExistingBuildingsM2PermanentArea", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<SiteDetailsAreaOfExistingBuildingsM2PermanentArea>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 8,
                unicode: false);
            siteDetailsAreaOfExistingBuildingsM2PermanentArea.AddAnnotation("Relational:ColumnName", "Site Details.Area of existing buildings m2 : Permanent Area");
            siteDetailsAreaOfExistingBuildingsM2PermanentArea.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var siteDetailsAreaOfExistingBuildingsM2TemporaryArea = runtimeEntityType.AddProperty(
                "SiteDetailsAreaOfExistingBuildingsM2TemporaryArea",
                typeof(string),
                propertyInfo: typeof(Construction).GetProperty("SiteDetailsAreaOfExistingBuildingsM2TemporaryArea", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<SiteDetailsAreaOfExistingBuildingsM2TemporaryArea>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 8,
                unicode: false);
            siteDetailsAreaOfExistingBuildingsM2TemporaryArea.AddAnnotation("Relational:ColumnName", "Site Details.Area of existing buildings m2 : Temporary Area");
            siteDetailsAreaOfExistingBuildingsM2TemporaryArea.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var siteDetailsAreaOfHardStandingM2 = runtimeEntityType.AddProperty(
                "SiteDetailsAreaOfHardStandingM2",
                typeof(string),
                propertyInfo: typeof(Construction).GetProperty("SiteDetailsAreaOfHardStandingM2", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<SiteDetailsAreaOfHardStandingM2>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 6,
                unicode: false);
            siteDetailsAreaOfHardStandingM2.AddAnnotation("Relational:ColumnName", "Site Details.Area of hard standing m2");
            siteDetailsAreaOfHardStandingM2.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var siteDetailsAreaOfMajorRefurbishmentM2 = runtimeEntityType.AddProperty(
                "SiteDetailsAreaOfMajorRefurbishmentM2",
                typeof(string),
                propertyInfo: typeof(Construction).GetProperty("SiteDetailsAreaOfMajorRefurbishmentM2", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<SiteDetailsAreaOfMajorRefurbishmentM2>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 6,
                unicode: false);
            siteDetailsAreaOfMajorRefurbishmentM2.AddAnnotation("Relational:ColumnName", "Site Details.Area of major refurbishment m2");
            siteDetailsAreaOfMajorRefurbishmentM2.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var siteDetailsAreaOfMinorRefurbishmentM2 = runtimeEntityType.AddProperty(
                "SiteDetailsAreaOfMinorRefurbishmentM2",
                typeof(string),
                propertyInfo: typeof(Construction).GetProperty("SiteDetailsAreaOfMinorRefurbishmentM2", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<SiteDetailsAreaOfMinorRefurbishmentM2>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 6,
                unicode: false);
            siteDetailsAreaOfMinorRefurbishmentM2.AddAnnotation("Relational:ColumnName", "Site Details.Area of minor refurbishment m2");
            siteDetailsAreaOfMinorRefurbishmentM2.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var siteDetailsAreaOfMugaPlayingFieldsM2 = runtimeEntityType.AddProperty(
                "SiteDetailsAreaOfMugaPlayingFieldsM2",
                typeof(string),
                propertyInfo: typeof(Construction).GetProperty("SiteDetailsAreaOfMugaPlayingFieldsM2", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<SiteDetailsAreaOfMugaPlayingFieldsM2>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 6,
                unicode: false);
            siteDetailsAreaOfMugaPlayingFieldsM2.AddAnnotation("Relational:ColumnName", "Site Details.Area of MUGA / playing fields m2");
            siteDetailsAreaOfMugaPlayingFieldsM2.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var siteDetailsAreaOfNewBuildM2 = runtimeEntityType.AddProperty(
                "SiteDetailsAreaOfNewBuildM2",
                typeof(string),
                propertyInfo: typeof(Construction).GetProperty("SiteDetailsAreaOfNewBuildM2", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<SiteDetailsAreaOfNewBuildM2>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 6,
                unicode: false);
            siteDetailsAreaOfNewBuildM2.AddAnnotation("Relational:ColumnName", "Site Details.Area of new build m2");
            siteDetailsAreaOfNewBuildM2.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var siteDetailsAreaOfRefreshM2 = runtimeEntityType.AddProperty(
                "SiteDetailsAreaOfRefreshM2",
                typeof(string),
                propertyInfo: typeof(Construction).GetProperty("SiteDetailsAreaOfRefreshM2", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<SiteDetailsAreaOfRefreshM2>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 6,
                unicode: false);
            siteDetailsAreaOfRefreshM2.AddAnnotation("Relational:ColumnName", "Site Details.Area of refresh m2");
            siteDetailsAreaOfRefreshM2.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var siteDetailsAreaOfRefurbishmentM2 = runtimeEntityType.AddProperty(
                "SiteDetailsAreaOfRefurbishmentM2",
                typeof(string),
                propertyInfo: typeof(Construction).GetProperty("SiteDetailsAreaOfRefurbishmentM2", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<SiteDetailsAreaOfRefurbishmentM2>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 6,
                unicode: false);
            siteDetailsAreaOfRefurbishmentM2.AddAnnotation("Relational:ColumnName", "Site Details.Area of refurbishment m2");
            siteDetailsAreaOfRefurbishmentM2.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var siteDetailsAreaOfTemporaryAccommodationRequiredM2 = runtimeEntityType.AddProperty(
                "SiteDetailsAreaOfTemporaryAccommodationRequiredM2",
                typeof(string),
                propertyInfo: typeof(Construction).GetProperty("SiteDetailsAreaOfTemporaryAccommodationRequiredM2", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<SiteDetailsAreaOfTemporaryAccommodationRequiredM2>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 6,
                unicode: false);
            siteDetailsAreaOfTemporaryAccommodationRequiredM2.AddAnnotation("Relational:ColumnName", "Site Details.Area of temporary accommodation required m2");
            siteDetailsAreaOfTemporaryAccommodationRequiredM2.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var siteDetailsLocation = runtimeEntityType.AddProperty(
                "SiteDetailsLocation",
                typeof(string),
                propertyInfo: typeof(Construction).GetProperty("SiteDetailsLocation", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<SiteDetailsLocation>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            siteDetailsLocation.AddAnnotation("Relational:ColumnName", "Site Details.Location");
            siteDetailsLocation.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var siteDetailsMaximumGrossAreaRequiredM2 = runtimeEntityType.AddProperty(
                "SiteDetailsMaximumGrossAreaRequiredM2",
                typeof(string),
                propertyInfo: typeof(Construction).GetProperty("SiteDetailsMaximumGrossAreaRequiredM2", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<SiteDetailsMaximumGrossAreaRequiredM2>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 6,
                unicode: false);
            siteDetailsMaximumGrossAreaRequiredM2.AddAnnotation("Relational:ColumnName", "Site Details.Maximum gross area required m2");
            siteDetailsMaximumGrossAreaRequiredM2.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var siteDetailsMinimumGrossAreaRequiredM2 = runtimeEntityType.AddProperty(
                "SiteDetailsMinimumGrossAreaRequiredM2",
                typeof(string),
                propertyInfo: typeof(Construction).GetProperty("SiteDetailsMinimumGrossAreaRequiredM2", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<SiteDetailsMinimumGrossAreaRequiredM2>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 6,
                unicode: false);
            siteDetailsMinimumGrossAreaRequiredM2.AddAnnotation("Relational:ColumnName", "Site Details.Minimum gross area required m2");
            siteDetailsMinimumGrossAreaRequiredM2.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var siteDetailsSprinklerInstallationType = runtimeEntityType.AddProperty(
                "SiteDetailsSprinklerInstallationType",
                typeof(string),
                propertyInfo: typeof(Construction).GetProperty("SiteDetailsSprinklerInstallationType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<SiteDetailsSprinklerInstallationType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            siteDetailsSprinklerInstallationType.AddAnnotation("Relational:ColumnName", "Site Details.Sprinkler Installation Type");
            siteDetailsSprinklerInstallationType.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var siteDetailsSprinklerType = runtimeEntityType.AddProperty(
                "SiteDetailsSprinklerType",
                typeof(string),
                propertyInfo: typeof(Construction).GetProperty("SiteDetailsSprinklerType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<SiteDetailsSprinklerType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            siteDetailsSprinklerType.AddAnnotation("Relational:ColumnName", "Site Details.Sprinkler Type");
            siteDetailsSprinklerType.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var siteDetailsSprinklers = runtimeEntityType.AddProperty(
                "SiteDetailsSprinklers",
                typeof(string),
                propertyInfo: typeof(Construction).GetProperty("SiteDetailsSprinklers", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<SiteDetailsSprinklers>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            siteDetailsSprinklers.AddAnnotation("Relational:ColumnName", "Site Details.Sprinklers");
            siteDetailsSprinklers.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var siteDetailsTypeOfWorks = runtimeEntityType.AddProperty(
                "SiteDetailsTypeOfWorks",
                typeof(string),
                propertyInfo: typeof(Construction).GetProperty("SiteDetailsTypeOfWorks", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Construction).GetField("<SiteDetailsTypeOfWorks>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            siteDetailsTypeOfWorks.AddAnnotation("Relational:ColumnName", "Site Details.Type of works");
            siteDetailsTypeOfWorks.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { rid });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "dbo");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Construction");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);
            runtimeEntityType.AddAnnotation("SqlServer:IsTemporal", true);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
