// <auto-generated />
using System;
using System.Reflection;
using Dfe.ManageFreeSchoolProjects.Data.Entities.Existing;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Dfe.ManageFreeSchoolProjects.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class FalEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Dfe.ManageFreeSchoolProjects.Data.Entities.Existing.Fal",
                typeof(Fal),
                baseEntityType,
                propertyCount: 13,
                keyCount: 1);

            var rid = runtimeEntityType.AddProperty(
                "Rid",
                typeof(string),
                propertyInfo: typeof(Fal).GetProperty("Rid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Fal).GetField("<Rid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 11,
                unicode: false);
            rid.AddAnnotation("Relational:ColumnName", "RID");
            rid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fundingApprovalLettersFundingApprovalLetterIssuedDate = runtimeEntityType.AddProperty(
                "FundingApprovalLettersFundingApprovalLetterIssuedDate",
                typeof(DateTime?),
                propertyInfo: typeof(Fal).GetProperty("FundingApprovalLettersFundingApprovalLetterIssuedDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Fal).GetField("<FundingApprovalLettersFundingApprovalLetterIssuedDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            fundingApprovalLettersFundingApprovalLetterIssuedDate.AddAnnotation("Relational:ColumnName", "Funding Approval Letters.Funding approval letter issued date");
            fundingApprovalLettersFundingApprovalLetterIssuedDate.AddAnnotation("Relational:ColumnType", "date");
            fundingApprovalLettersFundingApprovalLetterIssuedDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fundingApprovalLettersFundingApprovalLetterRecipient = runtimeEntityType.AddProperty(
                "FundingApprovalLettersFundingApprovalLetterRecipient",
                typeof(string),
                propertyInfo: typeof(Fal).GetProperty("FundingApprovalLettersFundingApprovalLetterRecipient", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Fal).GetField("<FundingApprovalLettersFundingApprovalLetterRecipient>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            fundingApprovalLettersFundingApprovalLetterRecipient.AddAnnotation("Relational:ColumnName", "Funding Approval Letters.Funding approval letter recipient");
            fundingApprovalLettersFundingApprovalLetterRecipient.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fundingApprovalLettersFundingApprovalLetterTotalValue = runtimeEntityType.AddProperty(
                "FundingApprovalLettersFundingApprovalLetterTotalValue",
                typeof(string),
                propertyInfo: typeof(Fal).GetProperty("FundingApprovalLettersFundingApprovalLetterTotalValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Fal).GetField("<FundingApprovalLettersFundingApprovalLetterTotalValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            fundingApprovalLettersFundingApprovalLetterTotalValue.AddAnnotation("Relational:ColumnName", "Funding Approval Letters.Funding approval letter Total value");
            fundingApprovalLettersFundingApprovalLetterTotalValue.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fundingApprovalLettersId = runtimeEntityType.AddProperty(
                "FundingApprovalLettersId",
                typeof(string),
                propertyInfo: typeof(Fal).GetProperty("FundingApprovalLettersId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Fal).GetField("<FundingApprovalLettersId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            fundingApprovalLettersId.AddAnnotation("Relational:ColumnName", "Funding Approval Letters.ID");
            fundingApprovalLettersId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fundingApprovalLettersLinkToFundingApprovalLetter = runtimeEntityType.AddProperty(
                "FundingApprovalLettersLinkToFundingApprovalLetter",
                typeof(string),
                propertyInfo: typeof(Fal).GetProperty("FundingApprovalLettersLinkToFundingApprovalLetter", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Fal).GetField("<FundingApprovalLettersLinkToFundingApprovalLetter>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            fundingApprovalLettersLinkToFundingApprovalLetter.AddAnnotation("Relational:ColumnName", "Funding Approval Letters.Link to funding approval letter");
            fundingApprovalLettersLinkToFundingApprovalLetter.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fundingApprovalLettersTotalConstruction = runtimeEntityType.AddProperty(
                "FundingApprovalLettersTotalConstruction",
                typeof(string),
                propertyInfo: typeof(Fal).GetProperty("FundingApprovalLettersTotalConstruction", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Fal).GetField("<FundingApprovalLettersTotalConstruction>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            fundingApprovalLettersTotalConstruction.AddAnnotation("Relational:ColumnName", "Funding Approval Letters.Total construction");
            fundingApprovalLettersTotalConstruction.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fundingApprovalLettersTotalFfEBudget = runtimeEntityType.AddProperty(
                "FundingApprovalLettersTotalFfEBudget",
                typeof(string),
                propertyInfo: typeof(Fal).GetProperty("FundingApprovalLettersTotalFfEBudget", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Fal).GetField("<FundingApprovalLettersTotalFfEBudget>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            fundingApprovalLettersTotalFfEBudget.AddAnnotation("Relational:ColumnName", "Funding Approval Letters.Total FF&E budget");
            fundingApprovalLettersTotalFfEBudget.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fundingApprovalLettersTotalIctBudget = runtimeEntityType.AddProperty(
                "FundingApprovalLettersTotalIctBudget",
                typeof(string),
                propertyInfo: typeof(Fal).GetProperty("FundingApprovalLettersTotalIctBudget", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Fal).GetField("<FundingApprovalLettersTotalIctBudget>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            fundingApprovalLettersTotalIctBudget.AddAnnotation("Relational:ColumnName", "Funding Approval Letters.Total ICT budget");
            fundingApprovalLettersTotalIctBudget.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fundingApprovalLettersTotalTemporarySiteBudget = runtimeEntityType.AddProperty(
                "FundingApprovalLettersTotalTemporarySiteBudget",
                typeof(string),
                propertyInfo: typeof(Fal).GetProperty("FundingApprovalLettersTotalTemporarySiteBudget", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Fal).GetField("<FundingApprovalLettersTotalTemporarySiteBudget>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            fundingApprovalLettersTotalTemporarySiteBudget.AddAnnotation("Relational:ColumnName", "Funding Approval Letters.Total temporary site budget");
            fundingApprovalLettersTotalTemporarySiteBudget.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var pRid = runtimeEntityType.AddProperty(
                "PRid",
                typeof(string),
                propertyInfo: typeof(Fal).GetProperty("PRid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Fal).GetField("<PRid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 11,
                unicode: false);
            pRid.AddAnnotation("Relational:ColumnName", "p_rid");
            pRid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var periodEnd = runtimeEntityType.AddProperty(
                "PeriodEnd",
                typeof(DateTime),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            periodEnd.AddAnnotation("Relational:ColumnName", "PeriodEnd");
            periodEnd.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var periodStart = runtimeEntityType.AddProperty(
                "PeriodStart",
                typeof(DateTime),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            periodStart.AddAnnotation("Relational:ColumnName", "PeriodStart");
            periodStart.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { rid });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "dbo");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "FAL");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);
            runtimeEntityType.AddAnnotation("SqlServer:IsTemporal", true);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
