// <auto-generated />
using System;
using System.Reflection;
using Dfe.ManageFreeSchoolProjects.Data.Entities.Existing;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Dfe.ManageFreeSchoolProjects.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class LaDataEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Dfe.ManageFreeSchoolProjects.Data.Entities.Existing.LaData",
                typeof(LaData),
                baseEntityType,
                propertyCount: 9,
                keyCount: 1);

            var localAuthoritiesLaCode = runtimeEntityType.AddProperty(
                "LocalAuthoritiesLaCode",
                typeof(string),
                propertyInfo: typeof(LaData).GetProperty("LocalAuthoritiesLaCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(LaData).GetField("<LocalAuthoritiesLaCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 100,
                unicode: false);
            localAuthoritiesLaCode.AddAnnotation("Relational:ColumnName", "Local Authorities.LA Code");
            localAuthoritiesLaCode.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var localAuthoritiesCapitalCostTier = runtimeEntityType.AddProperty(
                "LocalAuthoritiesCapitalCostTier",
                typeof(string),
                propertyInfo: typeof(LaData).GetProperty("LocalAuthoritiesCapitalCostTier", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(LaData).GetField("<LocalAuthoritiesCapitalCostTier>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            localAuthoritiesCapitalCostTier.AddAnnotation("Relational:ColumnName", "Local Authorities.Capital cost tier");
            localAuthoritiesCapitalCostTier.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var localAuthoritiesGeographicalRegion = runtimeEntityType.AddProperty(
                "LocalAuthoritiesGeographicalRegion",
                typeof(string),
                propertyInfo: typeof(LaData).GetProperty("LocalAuthoritiesGeographicalRegion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(LaData).GetField("<LocalAuthoritiesGeographicalRegion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            localAuthoritiesGeographicalRegion.AddAnnotation("Relational:ColumnName", "Local Authorities.Geographical region");
            localAuthoritiesGeographicalRegion.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var localAuthoritiesLaLondonBased = runtimeEntityType.AddProperty(
                "LocalAuthoritiesLaLondonBased",
                typeof(string),
                propertyInfo: typeof(LaData).GetProperty("LocalAuthoritiesLaLondonBased", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(LaData).GetField("<LocalAuthoritiesLaLondonBased>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            localAuthoritiesLaLondonBased.AddAnnotation("Relational:ColumnName", "Local Authorities.LA London Based");
            localAuthoritiesLaLondonBased.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var localAuthoritiesLaName = runtimeEntityType.AddProperty(
                "LocalAuthoritiesLaName",
                typeof(string),
                propertyInfo: typeof(LaData).GetProperty("LocalAuthoritiesLaName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(LaData).GetField("<LocalAuthoritiesLaName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            localAuthoritiesLaName.AddAnnotation("Relational:ColumnName", "Local Authorities.LA Name");
            localAuthoritiesLaName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var localAuthoritiesLondonNotLondon = runtimeEntityType.AddProperty(
                "LocalAuthoritiesLondonNotLondon",
                typeof(string),
                propertyInfo: typeof(LaData).GetProperty("LocalAuthoritiesLondonNotLondon", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(LaData).GetField("<LocalAuthoritiesLondonNotLondon>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            localAuthoritiesLondonNotLondon.AddAnnotation("Relational:ColumnName", "Local Authorities.London/Not London");
            localAuthoritiesLondonNotLondon.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var localAuthoritiesRscRegion = runtimeEntityType.AddProperty(
                "LocalAuthoritiesRscRegion",
                typeof(string),
                propertyInfo: typeof(LaData).GetProperty("LocalAuthoritiesRscRegion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(LaData).GetField("<LocalAuthoritiesRscRegion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            localAuthoritiesRscRegion.AddAnnotation("Relational:ColumnName", "Local Authorities.RSC Region");
            localAuthoritiesRscRegion.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var periodEnd = runtimeEntityType.AddProperty(
                "PeriodEnd",
                typeof(DateTime),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            periodEnd.AddAnnotation("Relational:ColumnName", "PeriodEnd");
            periodEnd.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var periodStart = runtimeEntityType.AddProperty(
                "PeriodStart",
                typeof(DateTime),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            periodStart.AddAnnotation("Relational:ColumnName", "PeriodStart");
            periodStart.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { localAuthoritiesLaCode });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "dbo");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "LA_Data");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);
            runtimeEntityType.AddAnnotation("SqlServer:IsTemporal", true);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
