// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Dfe.ManageFreeSchoolProjects.Data.CompiledModels
{
    public partial class MfspContextModel
    {
        private MfspContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("785a9a68-66cc-446b-b748-83cbd0e09f41"), entityTypeCount: 41)
        {
        }

        partial void Initialize()
        {
            var basicNeed = BasicNeedEntityType.Create(this);
            var br = BrEntityType.Create(this);
            var bs = BsEntityType.Create(this);
            var constructData = ConstructDataEntityType.Create(this);
            var construction = ConstructionEntityType.Create(this);
            var contracts = ContractsEntityType.Create(this);
            var fal = FalEntityType.Create(this);
            var fsKim = FsKimEntityType.Create(this);
            var kai = KaiEntityType.Create(this);
            var kpi = KpiEntityType.Create(this);
            var laData = LaDataEntityType.Create(this);
            var milestones = MilestonesEntityType.Create(this);
            var ofstedArchive = OfstedArchiveEntityType.Create(this);
            var ofstedFsg = OfstedFsgEntityType.Create(this);
            var opens = OpensEntityType.Create(this);
            var pdfd = PdfdEntityType.Create(this);
            var pdfdArchive = PdfdArchiveEntityType.Create(this);
            var pdgl = PdglEntityType.Create(this);
            var perfFsg = PerfFsgEntityType.Create(this);
            var perfFsgLocal = PerfFsgLocalEntityType.Create(this);
            var planning = PlanningEntityType.Create(this);
            var planningQa = PlanningQaEntityType.Create(this);
            var po = PoEntityType.Create(this);
            var porf = PorfEntityType.Create(this);
            var pr = PrEntityType.Create(this);
            var property = PropertyEntityType.Create(this);
            var propertyQa = PropertyQaEntityType.Create(this);
            var rag = RagEntityType.Create(this);
            var ragtempBudget = RagtempBudgetEntityType.Create(this);
            var ragtempRatings = RagtempRatingsEntityType.Create(this);
            var regionalFramework = RegionalFrameworkEntityType.Create(this);
            var reportServerUrl = ReportServerUrlEntityType.Create(this);
            var tally = TallyEntityType.Create(this);
            var tasks = TasksEntityType.Create(this);
            var technicalQa = TechnicalQaEntityType.Create(this);
            var termVisits = TermVisitsEntityType.Create(this);
            var termVisitsUtcs = TermVisitsUtcsEntityType.Create(this);
            var trust = TrustEntityType.Create(this);
            var wfa = WfaEntityType.Create(this);
            var riskAppraisalMeetingTask = RiskAppraisalMeetingTaskEntityType.Create(this);
            var user = UserEntityType.Create(this);

            BsEntityType.CreateForeignKey1(bs, user);
            ConstructDataEntityType.CreateForeignKey1(constructData, user);
            FsKimEntityType.CreateForeignKey1(fsKim, user);
            KaiEntityType.CreateForeignKey1(kai, user);
            KpiEntityType.CreateForeignKey1(kpi, user);
            KpiEntityType.CreateForeignKey2(kpi, user);
            MilestonesEntityType.CreateForeignKey1(milestones, user);
            OfstedFsgEntityType.CreateForeignKey1(ofstedFsg, user);
            OpensEntityType.CreateForeignKey1(opens, user);
            PoEntityType.CreateForeignKey1(po, user);
            PropertyEntityType.CreateForeignKey1(property, user);
            RagEntityType.CreateForeignKey1(rag, user);
            TasksEntityType.CreateForeignKey1(tasks, user);
            RiskAppraisalMeetingTaskEntityType.CreateForeignKey1(riskAppraisalMeetingTask, user);

            BasicNeedEntityType.CreateAnnotations(basicNeed);
            BrEntityType.CreateAnnotations(br);
            BsEntityType.CreateAnnotations(bs);
            ConstructDataEntityType.CreateAnnotations(constructData);
            ConstructionEntityType.CreateAnnotations(construction);
            ContractsEntityType.CreateAnnotations(contracts);
            FalEntityType.CreateAnnotations(fal);
            FsKimEntityType.CreateAnnotations(fsKim);
            KaiEntityType.CreateAnnotations(kai);
            KpiEntityType.CreateAnnotations(kpi);
            LaDataEntityType.CreateAnnotations(laData);
            MilestonesEntityType.CreateAnnotations(milestones);
            OfstedArchiveEntityType.CreateAnnotations(ofstedArchive);
            OfstedFsgEntityType.CreateAnnotations(ofstedFsg);
            OpensEntityType.CreateAnnotations(opens);
            PdfdEntityType.CreateAnnotations(pdfd);
            PdfdArchiveEntityType.CreateAnnotations(pdfdArchive);
            PdglEntityType.CreateAnnotations(pdgl);
            PerfFsgEntityType.CreateAnnotations(perfFsg);
            PerfFsgLocalEntityType.CreateAnnotations(perfFsgLocal);
            PlanningEntityType.CreateAnnotations(planning);
            PlanningQaEntityType.CreateAnnotations(planningQa);
            PoEntityType.CreateAnnotations(po);
            PorfEntityType.CreateAnnotations(porf);
            PrEntityType.CreateAnnotations(pr);
            PropertyEntityType.CreateAnnotations(property);
            PropertyQaEntityType.CreateAnnotations(propertyQa);
            RagEntityType.CreateAnnotations(rag);
            RagtempBudgetEntityType.CreateAnnotations(ragtempBudget);
            RagtempRatingsEntityType.CreateAnnotations(ragtempRatings);
            RegionalFrameworkEntityType.CreateAnnotations(regionalFramework);
            ReportServerUrlEntityType.CreateAnnotations(reportServerUrl);
            TallyEntityType.CreateAnnotations(tally);
            TasksEntityType.CreateAnnotations(tasks);
            TechnicalQaEntityType.CreateAnnotations(technicalQa);
            TermVisitsEntityType.CreateAnnotations(termVisits);
            TermVisitsUtcsEntityType.CreateAnnotations(termVisitsUtcs);
            TrustEntityType.CreateAnnotations(trust);
            WfaEntityType.CreateAnnotations(wfa);
            RiskAppraisalMeetingTaskEntityType.CreateAnnotations(riskAppraisalMeetingTask);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("ProductVersion", "10.0.6");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
