// <auto-generated />
using System;
using System.Reflection;
using Dfe.ManageFreeSchoolProjects.Data.Entities.Existing;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Dfe.ManageFreeSchoolProjects.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class PerfFsgEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Dfe.ManageFreeSchoolProjects.Data.Entities.Existing.PerfFsg",
                typeof(PerfFsg),
                baseEntityType,
                propertyCount: 102,
                keyCount: 1);

            var rid = runtimeEntityType.AddProperty(
                "Rid",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("Rid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<Rid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 11,
                unicode: false);
            rid.AddAnnotation("Relational:ColumnName", "RID");
            rid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var pRid = runtimeEntityType.AddProperty(
                "PRid",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("PRid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<PRid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 11,
                unicode: false);
            pRid.AddAnnotation("Relational:ColumnName", "p_rid");
            pRid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var periodEnd = runtimeEntityType.AddProperty(
                "PeriodEnd",
                typeof(DateTime),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            periodEnd.AddAnnotation("Relational:ColumnName", "PeriodEnd");
            periodEnd.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var periodStart = runtimeEntityType.AddProperty(
                "PeriodStart",
                typeof(DateTime),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            periodStart.AddAnnotation("Relational:ColumnName", "PeriodStart");
            periodStart.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs1Ks2ValueAdded = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs1Ks2ValueAdded",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs1Ks2ValueAdded", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs1Ks2ValueAdded>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs1Ks2ValueAdded.AddAnnotation("Relational:ColumnName", "School Performance Data.KS1-KS2 value added");
            schoolPerformanceDataKs1Ks2ValueAdded.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2AverageScoreInMaths = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2AverageScoreInMaths",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2AverageScoreInMaths", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2AverageScoreInMaths>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2AverageScoreInMaths.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 Average score in maths");
            schoolPerformanceDataKs2AverageScoreInMaths.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2AverageScoreInReading = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2AverageScoreInReading",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2AverageScoreInReading", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2AverageScoreInReading>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2AverageScoreInReading.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 Average score in reading");
            schoolPerformanceDataKs2AverageScoreInReading.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2EngProgress = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2EngProgress",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2EngProgress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2EngProgress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2EngProgress.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 Eng progress");
            schoolPerformanceDataKs2EngProgress.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2ExpectedStandardInMaths = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2ExpectedStandardInMaths",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2ExpectedStandardInMaths", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2ExpectedStandardInMaths>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2ExpectedStandardInMaths.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 expected standard in maths");
            schoolPerformanceDataKs2ExpectedStandardInMaths.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2ExpectedStandardInReading = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2ExpectedStandardInReading",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2ExpectedStandardInReading", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2ExpectedStandardInReading>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2ExpectedStandardInReading.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 expected standard in reading");
            schoolPerformanceDataKs2ExpectedStandardInReading.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2ExpectedStandardInReadingWritingAndMaths = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2ExpectedStandardInReadingWritingAndMaths",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2ExpectedStandardInReadingWritingAndMaths", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2ExpectedStandardInReadingWritingAndMaths>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2ExpectedStandardInReadingWritingAndMaths.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 expected standard in reading writing and maths");
            schoolPerformanceDataKs2ExpectedStandardInReadingWritingAndMaths.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2ExpectedStandardInWriting = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2ExpectedStandardInWriting",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2ExpectedStandardInWriting", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2ExpectedStandardInWriting>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2ExpectedStandardInWriting.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 expected standard in writing");
            schoolPerformanceDataKs2ExpectedStandardInWriting.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2HighInMaths = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2HighInMaths",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2HighInMaths", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2HighInMaths>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2HighInMaths.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 high in maths");
            schoolPerformanceDataKs2HighInMaths.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2HighInReading = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2HighInReading",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2HighInReading", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2HighInReading>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2HighInReading.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 high in reading");
            schoolPerformanceDataKs2HighInReading.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2HighInReadingWritingAndMaths = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2HighInReadingWritingAndMaths",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2HighInReadingWritingAndMaths", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2HighInReadingWritingAndMaths>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2HighInReadingWritingAndMaths.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 high in reading, writing and maths");
            schoolPerformanceDataKs2HighInReadingWritingAndMaths.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2HighInWriting = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2HighInWriting",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2HighInWriting", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2HighInWriting>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2HighInWriting.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 high in writing");
            schoolPerformanceDataKs2HighInWriting.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2Ks4ValueAdded = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2Ks4ValueAdded",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2Ks4ValueAdded", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2Ks4ValueAdded>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2Ks4ValueAdded.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2-KS4 value added");
            schoolPerformanceDataKs2Ks4ValueAdded.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2Ks4ValueAddedPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2Ks4ValueAddedPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2Ks4ValueAddedPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2Ks4ValueAddedPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2Ks4ValueAddedPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2-KS4 value added Pr");
            schoolPerformanceDataKs2Ks4ValueAddedPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2Level4EngMaths = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2Level4EngMaths",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2Level4EngMaths", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2Level4EngMaths>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2Level4EngMaths.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 level 4+ Eng maths");
            schoolPerformanceDataKs2Level4EngMaths.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2Level4Maths = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2Level4Maths",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2Level4Maths", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2Level4Maths>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2Level4Maths.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 level 4+ maths");
            schoolPerformanceDataKs2Level4Maths.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2Level4ReadWriteMaths = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2Level4ReadWriteMaths",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2Level4ReadWriteMaths", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2Level4ReadWriteMaths>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2Level4ReadWriteMaths.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 level 4+ read write maths");
            schoolPerformanceDataKs2Level4ReadWriteMaths.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2Level4Reading = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2Level4Reading",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2Level4Reading", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2Level4Reading>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2Level4Reading.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 level 4+ reading");
            schoolPerformanceDataKs2Level4Reading.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2Level4Writing = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2Level4Writing",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2Level4Writing", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2Level4Writing>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2Level4Writing.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 level 4+ writing");
            schoolPerformanceDataKs2Level4Writing.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2Level5EngMaths = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2Level5EngMaths",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2Level5EngMaths", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2Level5EngMaths>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2Level5EngMaths.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 level 5+ Eng maths");
            schoolPerformanceDataKs2Level5EngMaths.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2Level5Maths = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2Level5Maths",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2Level5Maths", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2Level5Maths>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2Level5Maths.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 level 5+ maths");
            schoolPerformanceDataKs2Level5Maths.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2Level5ReadWriteMaths = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2Level5ReadWriteMaths",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2Level5ReadWriteMaths", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2Level5ReadWriteMaths>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2Level5ReadWriteMaths.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 level 5+ read write maths");
            schoolPerformanceDataKs2Level5ReadWriteMaths.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2Level5Reading = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2Level5Reading",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2Level5Reading", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2Level5Reading>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2Level5Reading.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 level 5+ reading");
            schoolPerformanceDataKs2Level5Reading.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2Level5Writing = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2Level5Writing",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2Level5Writing", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2Level5Writing>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2Level5Writing.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 level 5+ writing");
            schoolPerformanceDataKs2Level5Writing.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2MathsProgress = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2MathsProgress",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2MathsProgress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2MathsProgress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2MathsProgress.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 maths progress");
            schoolPerformanceDataKs2MathsProgress.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2MathsProgressLowerConfidenceInterval = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2MathsProgressLowerConfidenceInterval",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2MathsProgressLowerConfidenceInterval", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2MathsProgressLowerConfidenceInterval>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2MathsProgressLowerConfidenceInterval.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 maths progress lower confidence interval");
            schoolPerformanceDataKs2MathsProgressLowerConfidenceInterval.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2MathsProgressScore = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2MathsProgressScore",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2MathsProgressScore", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2MathsProgressScore>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2MathsProgressScore.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 maths progress score");
            schoolPerformanceDataKs2MathsProgressScore.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2MathsProgressUpperConfidenceInterval = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2MathsProgressUpperConfidenceInterval",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2MathsProgressUpperConfidenceInterval", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2MathsProgressUpperConfidenceInterval>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2MathsProgressUpperConfidenceInterval.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 maths progress upper confidence interval");
            schoolPerformanceDataKs2MathsProgressUpperConfidenceInterval.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2Pupils = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2Pupils",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2Pupils", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2Pupils>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2Pupils.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 pupils");
            schoolPerformanceDataKs2Pupils.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2PupilsAchievingAHighScoreInReadingWritingAndMaths = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2PupilsAchievingAHighScoreInReadingWritingAndMaths",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2PupilsAchievingAHighScoreInReadingWritingAndMaths", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2PupilsAchievingAHighScoreInReadingWritingAndMaths>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2PupilsAchievingAHighScoreInReadingWritingAndMaths.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 pupils achieving a high score in reading, writing and maths");
            schoolPerformanceDataKs2PupilsAchievingAHighScoreInReadingWritingAndMaths.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2ReadProgress = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2ReadProgress",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2ReadProgress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2ReadProgress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2ReadProgress.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 read progress");
            schoolPerformanceDataKs2ReadProgress.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2ReadingProgressLowerConfidenceInterval = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2ReadingProgressLowerConfidenceInterval",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2ReadingProgressLowerConfidenceInterval", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2ReadingProgressLowerConfidenceInterval>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2ReadingProgressLowerConfidenceInterval.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 reading progress lower confidence interval");
            schoolPerformanceDataKs2ReadingProgressLowerConfidenceInterval.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2ReadingProgressScore = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2ReadingProgressScore",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2ReadingProgressScore", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2ReadingProgressScore>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2ReadingProgressScore.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 reading progress score");
            schoolPerformanceDataKs2ReadingProgressScore.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2ReadingProgressUpperConfidenceInterval = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2ReadingProgressUpperConfidenceInterval",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2ReadingProgressUpperConfidenceInterval", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2ReadingProgressUpperConfidenceInterval>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2ReadingProgressUpperConfidenceInterval.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 reading progress upper confidence interval");
            schoolPerformanceDataKs2ReadingProgressUpperConfidenceInterval.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2WriteProgress = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2WriteProgress",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2WriteProgress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2WriteProgress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2WriteProgress.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 write progress");
            schoolPerformanceDataKs2WriteProgress.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2WritingProgressLowerConfidenceInterval = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2WritingProgressLowerConfidenceInterval",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2WritingProgressLowerConfidenceInterval", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2WritingProgressLowerConfidenceInterval>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2WritingProgressLowerConfidenceInterval.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 writing progress lower confidence interval");
            schoolPerformanceDataKs2WritingProgressLowerConfidenceInterval.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2WritingProgressScore = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2WritingProgressScore",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2WritingProgressScore", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2WritingProgressScore>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2WritingProgressScore.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 writing progress score");
            schoolPerformanceDataKs2WritingProgressScore.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs2WritingProgressUpperConfidenceInterval = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs2WritingProgressUpperConfidenceInterval",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs2WritingProgressUpperConfidenceInterval", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs2WritingProgressUpperConfidenceInterval>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs2WritingProgressUpperConfidenceInterval.AddAnnotation("Relational:ColumnName", "School Performance Data.KS2 writing progress upper confidence interval");
            schoolPerformanceDataKs2WritingProgressUpperConfidenceInterval.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs45acIncEngMath = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs45acIncEngMath",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs45acIncEngMath", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs45acIncEngMath>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs45acIncEngMath.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 5AC inc Eng math");
            schoolPerformanceDataKs45acIncEngMath.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs45acIncEngMathPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs45acIncEngMathPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs45acIncEngMathPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs45acIncEngMathPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs45acIncEngMathPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 5AC inc Eng math Pr");
            schoolPerformanceDataKs45acIncEngMathPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs45acIncEngMathPupils = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs45acIncEngMathPupils",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs45acIncEngMathPupils", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs45acIncEngMathPupils>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs45acIncEngMathPupils.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 5AC inc Eng math Pupils");
            schoolPerformanceDataKs45acIncEngMathPupils.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4AchievingAStandardPass5OrAboveInEnglishAndMaths = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4AchievingAStandardPass5OrAboveInEnglishAndMaths",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4AchievingAStandardPass5OrAboveInEnglishAndMaths", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4AchievingAStandardPass5OrAboveInEnglishAndMaths>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4AchievingAStandardPass5OrAboveInEnglishAndMaths.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 achieving a ‘standard pass’ (5 or above) in English and maths");
            schoolPerformanceDataKs4AchievingAStandardPass5OrAboveInEnglishAndMaths.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4AchievingAStandardPass5OrAboveInEnglishAndMathsPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4AchievingAStandardPass5OrAboveInEnglishAndMathsPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4AchievingAStandardPass5OrAboveInEnglishAndMathsPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4AchievingAStandardPass5OrAboveInEnglishAndMathsPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4AchievingAStandardPass5OrAboveInEnglishAndMathsPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 achieving a ‘standard pass’ (5 or above) in English and maths Pr");
            schoolPerformanceDataKs4AchievingAStandardPass5OrAboveInEnglishAndMathsPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4AchievingAStrongPass5OrAboveInEnglishAndMaths = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4AchievingAStrongPass5OrAboveInEnglishAndMaths",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4AchievingAStrongPass5OrAboveInEnglishAndMaths", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4AchievingAStrongPass5OrAboveInEnglishAndMaths>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4AchievingAStrongPass5OrAboveInEnglishAndMaths.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 achieving a ‘strong pass’ (5 or above) in English and maths");
            schoolPerformanceDataKs4AchievingAStrongPass5OrAboveInEnglishAndMaths.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4AchievingAStrongPass5OrAboveInEnglishAndMathsPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4AchievingAStrongPass5OrAboveInEnglishAndMathsPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4AchievingAStrongPass5OrAboveInEnglishAndMathsPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4AchievingAStrongPass5OrAboveInEnglishAndMathsPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4AchievingAStrongPass5OrAboveInEnglishAndMathsPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 achieving a ‘strong pass’ (5 or above) in English and maths Pr");
            schoolPerformanceDataKs4AchievingAStrongPass5OrAboveInEnglishAndMathsPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4Attainment8Score = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4Attainment8Score",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4Attainment8Score", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4Attainment8Score>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4Attainment8Score.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 Attainment 8 score");
            schoolPerformanceDataKs4Attainment8Score.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4Attainment8ScoreEbacc = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4Attainment8ScoreEbacc",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4Attainment8ScoreEbacc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4Attainment8ScoreEbacc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4Attainment8ScoreEbacc.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 Attainment 8 score - Ebacc");
            schoolPerformanceDataKs4Attainment8ScoreEbacc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4Attainment8ScoreEnglish = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4Attainment8ScoreEnglish",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4Attainment8ScoreEnglish", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4Attainment8ScoreEnglish>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4Attainment8ScoreEnglish.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 Attainment 8 score - English");
            schoolPerformanceDataKs4Attainment8ScoreEnglish.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4Attainment8ScoreMaths = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4Attainment8ScoreMaths",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4Attainment8ScoreMaths", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4Attainment8ScoreMaths>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4Attainment8ScoreMaths.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 Attainment 8 score - Maths");
            schoolPerformanceDataKs4Attainment8ScoreMaths.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4Attainment8ScoreOpen = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4Attainment8ScoreOpen",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4Attainment8ScoreOpen", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4Attainment8ScoreOpen>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4Attainment8ScoreOpen.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 Attainment 8 score - Open");
            schoolPerformanceDataKs4Attainment8ScoreOpen.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4Attainment8ScorePr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4Attainment8ScorePr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4Attainment8ScorePr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4Attainment8ScorePr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4Attainment8ScorePr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 Attainment 8 score Pr");
            schoolPerformanceDataKs4Attainment8ScorePr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4CInEnglishAndMaths = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4CInEnglishAndMaths",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4CInEnglishAndMaths", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4CInEnglishAndMaths>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4CInEnglishAndMaths.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 C + in English and maths");
            schoolPerformanceDataKs4CInEnglishAndMaths.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4CInEnglishAndMathsPupils = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4CInEnglishAndMathsPupils",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4CInEnglishAndMathsPupils", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4CInEnglishAndMathsPupils>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4CInEnglishAndMathsPupils.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 C + in English and maths Pupils");
            schoolPerformanceDataKs4CInEnglishAndMathsPupils.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4Ebacc = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4Ebacc",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4Ebacc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4Ebacc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4Ebacc.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 EBacc");
            schoolPerformanceDataKs4Ebacc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4EbaccPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4EbaccPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4EbaccPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4EbaccPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4EbaccPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 EBacc Pr");
            schoolPerformanceDataKs4EbaccPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4EbaccPupils = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4EbaccPupils",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4EbaccPupils", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4EbaccPupils>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4EbaccPupils.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 Ebacc Pupils");
            schoolPerformanceDataKs4EbaccPupils.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4EngProgress = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4EngProgress",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4EngProgress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4EngProgress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4EngProgress.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 Eng progress");
            schoolPerformanceDataKs4EngProgress.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4EngProgressPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4EngProgressPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4EngProgressPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4EngProgressPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4EngProgressPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 Eng progress Pr");
            schoolPerformanceDataKs4EngProgressPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4MathsProgress = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4MathsProgress",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4MathsProgress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4MathsProgress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4MathsProgress.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 maths progress");
            schoolPerformanceDataKs4MathsProgress.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4MathsProgressPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4MathsProgressPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4MathsProgressPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4MathsProgressPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4MathsProgressPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 maths progress Pr");
            schoolPerformanceDataKs4MathsProgressPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4Progress8LowerConfidenceInterval = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4Progress8LowerConfidenceInterval",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4Progress8LowerConfidenceInterval", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4Progress8LowerConfidenceInterval>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4Progress8LowerConfidenceInterval.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 progress 8 lower confidence interval");
            schoolPerformanceDataKs4Progress8LowerConfidenceInterval.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4Progress8LowerConfidenceIntervalPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4Progress8LowerConfidenceIntervalPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4Progress8LowerConfidenceIntervalPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4Progress8LowerConfidenceIntervalPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4Progress8LowerConfidenceIntervalPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 progress 8 lower confidence interval Pr");
            schoolPerformanceDataKs4Progress8LowerConfidenceIntervalPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4Progress8Pupils = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4Progress8Pupils",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4Progress8Pupils", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4Progress8Pupils>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4Progress8Pupils.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 progress 8 pupils");
            schoolPerformanceDataKs4Progress8Pupils.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4Progress8PupilsPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4Progress8PupilsPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4Progress8PupilsPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4Progress8PupilsPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4Progress8PupilsPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 progress 8 pupils Pr");
            schoolPerformanceDataKs4Progress8PupilsPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4Progress8Score = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4Progress8Score",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4Progress8Score", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4Progress8Score>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4Progress8Score.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 progress 8 score");
            schoolPerformanceDataKs4Progress8Score.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4Progress8ScoreEbacc = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4Progress8ScoreEbacc",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4Progress8ScoreEbacc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4Progress8ScoreEbacc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4Progress8ScoreEbacc.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 progress 8 score -Ebacc");
            schoolPerformanceDataKs4Progress8ScoreEbacc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4Progress8ScoreEnglish = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4Progress8ScoreEnglish",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4Progress8ScoreEnglish", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4Progress8ScoreEnglish>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4Progress8ScoreEnglish.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 progress 8 score - English");
            schoolPerformanceDataKs4Progress8ScoreEnglish.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4Progress8ScoreMaths = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4Progress8ScoreMaths",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4Progress8ScoreMaths", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4Progress8ScoreMaths>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4Progress8ScoreMaths.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 progress 8 score - Maths");
            schoolPerformanceDataKs4Progress8ScoreMaths.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4Progress8ScoreOpen = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4Progress8ScoreOpen",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4Progress8ScoreOpen", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4Progress8ScoreOpen>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4Progress8ScoreOpen.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 progress 8 score - Open");
            schoolPerformanceDataKs4Progress8ScoreOpen.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4Progress8ScorePr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4Progress8ScorePr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4Progress8ScorePr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4Progress8ScorePr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4Progress8ScorePr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 progress 8 score Pr");
            schoolPerformanceDataKs4Progress8ScorePr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4Progress8UpperConfidenceInterval = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4Progress8UpperConfidenceInterval",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4Progress8UpperConfidenceInterval", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4Progress8UpperConfidenceInterval>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4Progress8UpperConfidenceInterval.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 progress 8 upper confidence interval");
            schoolPerformanceDataKs4Progress8UpperConfidenceInterval.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4Progress8UpperConfidenceIntervalPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4Progress8UpperConfidenceIntervalPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4Progress8UpperConfidenceIntervalPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4Progress8UpperConfidenceIntervalPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4Progress8UpperConfidenceIntervalPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 progress 8 upper confidence interval Pr");
            schoolPerformanceDataKs4Progress8UpperConfidenceIntervalPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4Pupils = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4Pupils",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4Pupils", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4Pupils>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4Pupils.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 pupils");
            schoolPerformanceDataKs4Pupils.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs4PupilsPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs4PupilsPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs4PupilsPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs4PupilsPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs4PupilsPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS4 pupils Pr");
            schoolPerformanceDataKs4PupilsPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5ApsPerEntryAcademic = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5ApsPerEntryAcademic",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5ApsPerEntryAcademic", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5ApsPerEntryAcademic>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5ApsPerEntryAcademic.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 APS per entry (Academic)");
            schoolPerformanceDataKs5ApsPerEntryAcademic.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5ApsPerEntryAcademicPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5ApsPerEntryAcademicPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5ApsPerEntryAcademicPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5ApsPerEntryAcademicPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5ApsPerEntryAcademicPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 APS per entry (Academic) Pr");
            schoolPerformanceDataKs5ApsPerEntryAcademicPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5ApsPerEntryAppliedGeneral = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5ApsPerEntryAppliedGeneral",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5ApsPerEntryAppliedGeneral", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5ApsPerEntryAppliedGeneral>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5ApsPerEntryAppliedGeneral.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 APS per entry (applied general)");
            schoolPerformanceDataKs5ApsPerEntryAppliedGeneral.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5ApsPerEntryVocational = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5ApsPerEntryVocational",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5ApsPerEntryVocational", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5ApsPerEntryVocational>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5ApsPerEntryVocational.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 APS per entry (Vocational)");
            schoolPerformanceDataKs5ApsPerEntryVocational.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5ApsPerEntryVocationalPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5ApsPerEntryVocationalPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5ApsPerEntryVocationalPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5ApsPerEntryVocationalPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5ApsPerEntryVocationalPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 APS per entry (Vocational) Pr");
            schoolPerformanceDataKs5ApsPerEntryVocationalPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5PupilsAcademic = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5PupilsAcademic",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5PupilsAcademic", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5PupilsAcademic>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5PupilsAcademic.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 pupils (academic)");
            schoolPerformanceDataKs5PupilsAcademic.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5PupilsAcademicPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5PupilsAcademicPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5PupilsAcademicPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5PupilsAcademicPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5PupilsAcademicPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 pupils (academic) Pr");
            schoolPerformanceDataKs5PupilsAcademicPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5PupilsAll = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5PupilsAll",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5PupilsAll", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5PupilsAll>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5PupilsAll.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 pupils (all)");
            schoolPerformanceDataKs5PupilsAll.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5PupilsAllPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5PupilsAllPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5PupilsAllPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5PupilsAllPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5PupilsAllPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 pupils (all)PR");
            schoolPerformanceDataKs5PupilsAllPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5PupilsAppliedGeneral = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5PupilsAppliedGeneral",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5PupilsAppliedGeneral", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5PupilsAppliedGeneral>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5PupilsAppliedGeneral.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 pupils (applied general)");
            schoolPerformanceDataKs5PupilsAppliedGeneral.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5PupilsAppliedGeneralPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5PupilsAppliedGeneralPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5PupilsAppliedGeneralPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5PupilsAppliedGeneralPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5PupilsAppliedGeneralPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 pupils (applied general) Pr");
            schoolPerformanceDataKs5PupilsAppliedGeneralPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5ValueAddedAcademic = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5ValueAddedAcademic",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5ValueAddedAcademic", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5ValueAddedAcademic>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5ValueAddedAcademic.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 value added (academic)");
            schoolPerformanceDataKs5ValueAddedAcademic.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5ValueAddedAcademicPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5ValueAddedAcademicPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5ValueAddedAcademicPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5ValueAddedAcademicPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5ValueAddedAcademicPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 value added (academic) Pr");
            schoolPerformanceDataKs5ValueAddedAcademicPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5ValueAddedAppliedGeneral = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5ValueAddedAppliedGeneral",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5ValueAddedAppliedGeneral", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5ValueAddedAppliedGeneral>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5ValueAddedAppliedGeneral.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 value added (applied general)");
            schoolPerformanceDataKs5ValueAddedAppliedGeneral.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5ValueAddedAppliedGeneralPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5ValueAddedAppliedGeneralPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5ValueAddedAppliedGeneralPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5ValueAddedAppliedGeneralPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5ValueAddedAppliedGeneralPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 value added (applied general) Pr");
            schoolPerformanceDataKs5ValueAddedAppliedGeneralPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5ValueAddedLowerConfidenceInterval = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5ValueAddedLowerConfidenceInterval",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5ValueAddedLowerConfidenceInterval", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5ValueAddedLowerConfidenceInterval>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5ValueAddedLowerConfidenceInterval.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 value added lower confidence interval");
            schoolPerformanceDataKs5ValueAddedLowerConfidenceInterval.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5ValueAddedLowerConfidenceIntervalPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5ValueAddedLowerConfidenceIntervalPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5ValueAddedLowerConfidenceIntervalPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5ValueAddedLowerConfidenceIntervalPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5ValueAddedLowerConfidenceIntervalPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 value added lower confidence interval Pr");
            schoolPerformanceDataKs5ValueAddedLowerConfidenceIntervalPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5ValueAddedUpperConfidenceInterval = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5ValueAddedUpperConfidenceInterval",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5ValueAddedUpperConfidenceInterval", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5ValueAddedUpperConfidenceInterval>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5ValueAddedUpperConfidenceInterval.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 value added upper confidence interval");
            schoolPerformanceDataKs5ValueAddedUpperConfidenceInterval.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5ValueAddedUpperConfidenceIntervalPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5ValueAddedUpperConfidenceIntervalPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5ValueAddedUpperConfidenceIntervalPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5ValueAddedUpperConfidenceIntervalPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5ValueAddedUpperConfidenceIntervalPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 value added upper confidence interval Pr");
            schoolPerformanceDataKs5ValueAddedUpperConfidenceIntervalPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5ValueAddedVocational = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5ValueAddedVocational",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5ValueAddedVocational", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5ValueAddedVocational>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5ValueAddedVocational.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 value added (Vocational)");
            schoolPerformanceDataKs5ValueAddedVocational.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataKs5ValueAddedVocationalPr = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataKs5ValueAddedVocationalPr",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataKs5ValueAddedVocationalPr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataKs5ValueAddedVocationalPr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataKs5ValueAddedVocationalPr.AddAnnotation("Relational:ColumnName", "School Performance Data.KS5 value added (Vocational) Pr");
            schoolPerformanceDataKs5ValueAddedVocationalPr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataNumberOfPupils = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataNumberOfPupils",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataNumberOfPupils", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataNumberOfPupils>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataNumberOfPupils.AddAnnotation("Relational:ColumnName", "School Performance Data.Number of pupils");
            schoolPerformanceDataNumberOfPupils.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataProgress8OptIn = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataProgress8OptIn",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataProgress8OptIn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataProgress8OptIn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            schoolPerformanceDataProgress8OptIn.AddAnnotation("Relational:ColumnName", "School Performance Data.Progress 8 opt in");
            schoolPerformanceDataProgress8OptIn.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schoolPerformanceDataYear = runtimeEntityType.AddProperty(
                "SchoolPerformanceDataYear",
                typeof(string),
                propertyInfo: typeof(PerfFsg).GetProperty("SchoolPerformanceDataYear", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsg).GetField("<SchoolPerformanceDataYear>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 4,
                unicode: false);
            schoolPerformanceDataYear.AddAnnotation("Relational:ColumnName", "School Performance Data.Year");
            schoolPerformanceDataYear.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { rid });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "dbo");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Perf_FSG");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);
            runtimeEntityType.AddAnnotation("SqlServer:IsTemporal", true);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
