// <auto-generated />
using System;
using System.Reflection;
using Dfe.ManageFreeSchoolProjects.Data.Entities.Existing;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Dfe.ManageFreeSchoolProjects.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class PerfFsgLocalEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Dfe.ManageFreeSchoolProjects.Data.Entities.Existing.PerfFsgLocal",
                typeof(PerfFsgLocal),
                baseEntityType,
                propertyCount: 13);

            var attainment8ScoreLaAverage = runtimeEntityType.AddProperty(
                "Attainment8ScoreLaAverage",
                typeof(string),
                propertyInfo: typeof(PerfFsgLocal).GetProperty("Attainment8ScoreLaAverage", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsgLocal).GetField("<Attainment8ScoreLaAverage>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            attainment8ScoreLaAverage.AddAnnotation("Relational:ColumnName", "Attainment 8 Score LA Average");
            attainment8ScoreLaAverage.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var inEducationPercentage = runtimeEntityType.AddProperty(
                "InEducationPercentage",
                typeof(string),
                propertyInfo: typeof(PerfFsgLocal).GetProperty("InEducationPercentage", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsgLocal).GetField("<InEducationPercentage>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            inEducationPercentage.AddAnnotation("Relational:ColumnName", "In Education (percentage)");
            inEducationPercentage.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ks4CInEnglishMathsLaAverage = runtimeEntityType.AddProperty(
                "Ks4CInEnglishMathsLaAverage",
                typeof(string),
                propertyInfo: typeof(PerfFsgLocal).GetProperty("Ks4CInEnglishMathsLaAverage", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsgLocal).GetField("<Ks4CInEnglishMathsLaAverage>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ks4CInEnglishMathsLaAverage.AddAnnotation("Relational:ColumnName", "KS4 C+ in English & Maths LA Average (%)");
            ks4CInEnglishMathsLaAverage.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ks4EbaccEnteredForEbacc = runtimeEntityType.AddProperty(
                "Ks4EbaccEnteredForEbacc",
                typeof(string),
                propertyInfo: typeof(PerfFsgLocal).GetProperty("Ks4EbaccEnteredForEbacc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsgLocal).GetField("<Ks4EbaccEnteredForEbacc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ks4EbaccEnteredForEbacc.AddAnnotation("Relational:ColumnName", "KS4 Ebacc (% entered for Ebacc)");
            ks4EbaccEnteredForEbacc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ks5ALevelApsPerEntry = runtimeEntityType.AddProperty(
                "Ks5ALevelApsPerEntry",
                typeof(string),
                propertyInfo: typeof(PerfFsgLocal).GetProperty("Ks5ALevelApsPerEntry", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsgLocal).GetField("<Ks5ALevelApsPerEntry>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ks5ALevelApsPerEntry.AddAnnotation("Relational:ColumnName", "KS5 A-Level (APS per Entry)");
            ks5ALevelApsPerEntry.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ks5AcademicProgressScore = runtimeEntityType.AddProperty(
                "Ks5AcademicProgressScore",
                typeof(string),
                propertyInfo: typeof(PerfFsgLocal).GetProperty("Ks5AcademicProgressScore", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsgLocal).GetField("<Ks5AcademicProgressScore>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ks5AcademicProgressScore.AddAnnotation("Relational:ColumnName", "KS5 Academic Progress Score");
            ks5AcademicProgressScore.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ks5AcademicProgressScoreAverageGrade = runtimeEntityType.AddProperty(
                "Ks5AcademicProgressScoreAverageGrade",
                typeof(string),
                propertyInfo: typeof(PerfFsgLocal).GetProperty("Ks5AcademicProgressScoreAverageGrade", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsgLocal).GetField("<Ks5AcademicProgressScoreAverageGrade>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ks5AcademicProgressScoreAverageGrade.AddAnnotation("Relational:ColumnName", "KS5 Academic Progress Score (Average Grade)");
            ks5AcademicProgressScoreAverageGrade.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ks5TechLevelApsPerEntry = runtimeEntityType.AddProperty(
                "Ks5TechLevelApsPerEntry",
                typeof(string),
                propertyInfo: typeof(PerfFsgLocal).GetProperty("Ks5TechLevelApsPerEntry", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsgLocal).GetField("<Ks5TechLevelApsPerEntry>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ks5TechLevelApsPerEntry.AddAnnotation("Relational:ColumnName", "KS5 Tech Level (APS per Entry)");
            ks5TechLevelApsPerEntry.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ks5TechLevelApsPerEntryLaAverage = runtimeEntityType.AddProperty(
                "Ks5TechLevelApsPerEntryLaAverage",
                typeof(string),
                propertyInfo: typeof(PerfFsgLocal).GetProperty("Ks5TechLevelApsPerEntryLaAverage", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsgLocal).GetField("<Ks5TechLevelApsPerEntryLaAverage>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ks5TechLevelApsPerEntryLaAverage.AddAnnotation("Relational:ColumnName", "KS5 Tech Level (APS per Entry - LA Average)");
            ks5TechLevelApsPerEntryLaAverage.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var projectId = runtimeEntityType.AddProperty(
                "ProjectId",
                typeof(string),
                propertyInfo: typeof(PerfFsgLocal).GetProperty("ProjectId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsgLocal).GetField("<ProjectId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 10,
                unicode: false);
            projectId.AddAnnotation("Relational:ColumnName", "Project ID");
            projectId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var totalOfStudentsStayingInEducationOrEmployment = runtimeEntityType.AddProperty(
                "TotalOfStudentsStayingInEducationOrEmployment",
                typeof(string),
                propertyInfo: typeof(PerfFsgLocal).GetProperty("TotalOfStudentsStayingInEducationOrEmployment", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsgLocal).GetField("<TotalOfStudentsStayingInEducationOrEmployment>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            totalOfStudentsStayingInEducationOrEmployment.AddAnnotation("Relational:ColumnName", "Total % of students staying in education or employment");
            totalOfStudentsStayingInEducationOrEmployment.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var urn = runtimeEntityType.AddProperty(
                "Urn",
                typeof(string),
                propertyInfo: typeof(PerfFsgLocal).GetProperty("Urn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsgLocal).GetField("<Urn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 10,
                unicode: false);
            urn.AddAnnotation("Relational:ColumnName", "URN");
            urn.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var year = runtimeEntityType.AddProperty(
                "Year",
                typeof(string),
                propertyInfo: typeof(PerfFsgLocal).GetProperty("Year", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfFsgLocal).GetField("<Year>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 4,
                unicode: false);
            year.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "dbo");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Perf_FSG_Local");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
