// <auto-generated />
using System;
using System.Reflection;
using Dfe.ManageFreeSchoolProjects.Data.Entities.Existing;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Dfe.ManageFreeSchoolProjects.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class PlanningEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Dfe.ManageFreeSchoolProjects.Data.Entities.Existing.Planning",
                typeof(Planning),
                baseEntityType,
                propertyCount: 44,
                keyCount: 1);

            var rid = runtimeEntityType.AddProperty(
                "Rid",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("Rid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<Rid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 11,
                unicode: false);
            rid.AddAnnotation("Relational:ColumnName", "RID");
            rid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var pRid = runtimeEntityType.AddProperty(
                "PRid",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PRid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PRid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 11,
                unicode: false);
            pRid.AddAnnotation("Relational:ColumnName", "p_rid");
            pRid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var periodEnd = runtimeEntityType.AddProperty(
                "PeriodEnd",
                typeof(DateTime),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            periodEnd.AddAnnotation("Relational:ColumnName", "PeriodEnd");
            periodEnd.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var periodStart = runtimeEntityType.AddProperty(
                "PeriodStart",
                typeof(DateTime),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            periodStart.AddAnnotation("Relational:ColumnName", "PeriodStart");
            periodStart.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordAddressManualOverwrite = runtimeEntityType.AddProperty(
                "PlanningRecordAddressManualOverwrite",
                typeof(bool?),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordAddressManualOverwrite", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordAddressManualOverwrite>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            planningRecordAddressManualOverwrite.AddAnnotation("Relational:ColumnName", "Planning Record.Address - Manual overwrite?");
            planningRecordAddressManualOverwrite.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordAddressOfSite = runtimeEntityType.AddProperty(
                "PlanningRecordAddressOfSite",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordAddressOfSite", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordAddressOfSite>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            planningRecordAddressOfSite.AddAnnotation("Relational:ColumnName", "Planning Record.Address of site");
            planningRecordAddressOfSite.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordAppealDecision = runtimeEntityType.AddProperty(
                "PlanningRecordAppealDecision",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordAppealDecision", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordAppealDecision>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            planningRecordAppealDecision.AddAnnotation("Relational:ColumnName", "Planning Record.Appeal decision");
            planningRecordAppealDecision.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordAppealProcedure = runtimeEntityType.AddProperty(
                "PlanningRecordAppealProcedure",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordAppealProcedure", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordAppealProcedure>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            planningRecordAppealProcedure.AddAnnotation("Relational:ColumnName", "Planning Record.Appeal procedure");
            planningRecordAppealProcedure.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordAppealRequired = runtimeEntityType.AddProperty(
                "PlanningRecordAppealRequired",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordAppealRequired", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordAppealRequired>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            planningRecordAppealRequired.AddAnnotation("Relational:ColumnName", "Planning Record.Appeal required?");
            planningRecordAppealRequired.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordClassCExpiryDateActual = runtimeEntityType.AddProperty(
                "PlanningRecordClassCExpiryDateActual",
                typeof(DateTime?),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordClassCExpiryDateActual", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordClassCExpiryDateActual>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            planningRecordClassCExpiryDateActual.AddAnnotation("Relational:ColumnName", "Planning Record.Class C expiry date (Actual)");
            planningRecordClassCExpiryDateActual.AddAnnotation("Relational:ColumnType", "date");
            planningRecordClassCExpiryDateActual.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordDateAppealSubmittedActual = runtimeEntityType.AddProperty(
                "PlanningRecordDateAppealSubmittedActual",
                typeof(DateTime?),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordDateAppealSubmittedActual", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordDateAppealSubmittedActual>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            planningRecordDateAppealSubmittedActual.AddAnnotation("Relational:ColumnName", "Planning Record.Date appeal submitted (actual)");
            planningRecordDateAppealSubmittedActual.AddAnnotation("Relational:ColumnType", "date");
            planningRecordDateAppealSubmittedActual.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordDateAppealSubmittedForecast = runtimeEntityType.AddProperty(
                "PlanningRecordDateAppealSubmittedForecast",
                typeof(DateTime?),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordDateAppealSubmittedForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordDateAppealSubmittedForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            planningRecordDateAppealSubmittedForecast.AddAnnotation("Relational:ColumnName", "Planning Record.Date appeal submitted (forecast)");
            planningRecordDateAppealSubmittedForecast.AddAnnotation("Relational:ColumnType", "date");
            planningRecordDateAppealSubmittedForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordDateAppealValidatedActual = runtimeEntityType.AddProperty(
                "PlanningRecordDateAppealValidatedActual",
                typeof(DateTime?),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordDateAppealValidatedActual", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordDateAppealValidatedActual>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            planningRecordDateAppealValidatedActual.AddAnnotation("Relational:ColumnName", "Planning Record.Date appeal validated (actual)");
            planningRecordDateAppealValidatedActual.AddAnnotation("Relational:ColumnType", "date");
            planningRecordDateAppealValidatedActual.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordDateLetterSentToLocalPlanningAuthorityActual = runtimeEntityType.AddProperty(
                "PlanningRecordDateLetterSentToLocalPlanningAuthorityActual",
                typeof(DateTime?),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordDateLetterSentToLocalPlanningAuthorityActual", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordDateLetterSentToLocalPlanningAuthorityActual>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            planningRecordDateLetterSentToLocalPlanningAuthorityActual.AddAnnotation("Relational:ColumnName", "Planning Record.Date letter sent to local planning authority (Actual)");
            planningRecordDateLetterSentToLocalPlanningAuthorityActual.AddAnnotation("Relational:ColumnType", "date");
            planningRecordDateLetterSentToLocalPlanningAuthorityActual.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordDateLetterSentToLocalPlanningAuthorityForecast = runtimeEntityType.AddProperty(
                "PlanningRecordDateLetterSentToLocalPlanningAuthorityForecast",
                typeof(DateTime?),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordDateLetterSentToLocalPlanningAuthorityForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordDateLetterSentToLocalPlanningAuthorityForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            planningRecordDateLetterSentToLocalPlanningAuthorityForecast.AddAnnotation("Relational:ColumnName", "Planning Record.Date letter sent to local planning authority (Forecast)");
            planningRecordDateLetterSentToLocalPlanningAuthorityForecast.AddAnnotation("Relational:ColumnType", "date");
            planningRecordDateLetterSentToLocalPlanningAuthorityForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordDateOfAppealDecisionNoticeActual = runtimeEntityType.AddProperty(
                "PlanningRecordDateOfAppealDecisionNoticeActual",
                typeof(DateTime?),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordDateOfAppealDecisionNoticeActual", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordDateOfAppealDecisionNoticeActual>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            planningRecordDateOfAppealDecisionNoticeActual.AddAnnotation("Relational:ColumnName", "Planning Record.Date of appeal decision notice (actual)");
            planningRecordDateOfAppealDecisionNoticeActual.AddAnnotation("Relational:ColumnType", "date");
            planningRecordDateOfAppealDecisionNoticeActual.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordDateOfAppealDecisionNoticeForecast = runtimeEntityType.AddProperty(
                "PlanningRecordDateOfAppealDecisionNoticeForecast",
                typeof(DateTime?),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordDateOfAppealDecisionNoticeForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordDateOfAppealDecisionNoticeForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            planningRecordDateOfAppealDecisionNoticeForecast.AddAnnotation("Relational:ColumnName", "Planning Record.Date of appeal decision notice (forecast)");
            planningRecordDateOfAppealDecisionNoticeForecast.AddAnnotation("Relational:ColumnType", "date");
            planningRecordDateOfAppealDecisionNoticeForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordDateOfPlanningDecisionNoticeActual = runtimeEntityType.AddProperty(
                "PlanningRecordDateOfPlanningDecisionNoticeActual",
                typeof(DateTime?),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordDateOfPlanningDecisionNoticeActual", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordDateOfPlanningDecisionNoticeActual>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            planningRecordDateOfPlanningDecisionNoticeActual.AddAnnotation("Relational:ColumnName", "Planning Record.Date of planning decision notice (actual)");
            planningRecordDateOfPlanningDecisionNoticeActual.AddAnnotation("Relational:ColumnType", "date");
            planningRecordDateOfPlanningDecisionNoticeActual.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordDateOfPlanningDecisionNoticeForecast = runtimeEntityType.AddProperty(
                "PlanningRecordDateOfPlanningDecisionNoticeForecast",
                typeof(DateTime?),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordDateOfPlanningDecisionNoticeForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordDateOfPlanningDecisionNoticeForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            planningRecordDateOfPlanningDecisionNoticeForecast.AddAnnotation("Relational:ColumnName", "Planning Record.Date of planning decision notice (forecast)");
            planningRecordDateOfPlanningDecisionNoticeForecast.AddAnnotation("Relational:ColumnType", "date");
            planningRecordDateOfPlanningDecisionNoticeForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordDateOfStatutoryDeterminationActual = runtimeEntityType.AddProperty(
                "PlanningRecordDateOfStatutoryDeterminationActual",
                typeof(DateTime?),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordDateOfStatutoryDeterminationActual", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordDateOfStatutoryDeterminationActual>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            planningRecordDateOfStatutoryDeterminationActual.AddAnnotation("Relational:ColumnName", "Planning Record.Date of statutory determination (actual)");
            planningRecordDateOfStatutoryDeterminationActual.AddAnnotation("Relational:ColumnType", "date");
            planningRecordDateOfStatutoryDeterminationActual.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordDatePlanningApplicationSubmittedActual = runtimeEntityType.AddProperty(
                "PlanningRecordDatePlanningApplicationSubmittedActual",
                typeof(DateTime?),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordDatePlanningApplicationSubmittedActual", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordDatePlanningApplicationSubmittedActual>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            planningRecordDatePlanningApplicationSubmittedActual.AddAnnotation("Relational:ColumnName", "Planning Record.Date planning application submitted (actual)");
            planningRecordDatePlanningApplicationSubmittedActual.AddAnnotation("Relational:ColumnType", "date");
            planningRecordDatePlanningApplicationSubmittedActual.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordDatePlanningApplicationSubmittedForecast = runtimeEntityType.AddProperty(
                "PlanningRecordDatePlanningApplicationSubmittedForecast",
                typeof(DateTime?),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordDatePlanningApplicationSubmittedForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordDatePlanningApplicationSubmittedForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            planningRecordDatePlanningApplicationSubmittedForecast.AddAnnotation("Relational:ColumnName", "Planning Record.Date planning application submitted (forecast)");
            planningRecordDatePlanningApplicationSubmittedForecast.AddAnnotation("Relational:ColumnType", "date");
            planningRecordDatePlanningApplicationSubmittedForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordDatePlanningApplicationValidatedActual = runtimeEntityType.AddProperty(
                "PlanningRecordDatePlanningApplicationValidatedActual",
                typeof(DateTime?),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordDatePlanningApplicationValidatedActual", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordDatePlanningApplicationValidatedActual>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            planningRecordDatePlanningApplicationValidatedActual.AddAnnotation("Relational:ColumnName", "Planning Record.Date planning application validated (actual)");
            planningRecordDatePlanningApplicationValidatedActual.AddAnnotation("Relational:ColumnType", "date");
            planningRecordDatePlanningApplicationValidatedActual.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordDatePlanningAppraisalCompletedActual = runtimeEntityType.AddProperty(
                "PlanningRecordDatePlanningAppraisalCompletedActual",
                typeof(DateTime?),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordDatePlanningAppraisalCompletedActual", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordDatePlanningAppraisalCompletedActual>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            planningRecordDatePlanningAppraisalCompletedActual.AddAnnotation("Relational:ColumnName", "Planning Record.Date planning appraisal completed (actual)");
            planningRecordDatePlanningAppraisalCompletedActual.AddAnnotation("Relational:ColumnType", "date");
            planningRecordDatePlanningAppraisalCompletedActual.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordDescriptionOfDevelopment = runtimeEntityType.AddProperty(
                "PlanningRecordDescriptionOfDevelopment",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordDescriptionOfDevelopment", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordDescriptionOfDevelopment>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                unicode: false);
            planningRecordDescriptionOfDevelopment.AddAnnotation("Relational:ColumnName", "Planning Record.Description of development");
            planningRecordDescriptionOfDevelopment.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordIsPlanningPermissionRequired = runtimeEntityType.AddProperty(
                "PlanningRecordIsPlanningPermissionRequired",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordIsPlanningPermissionRequired", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordIsPlanningPermissionRequired>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            planningRecordIsPlanningPermissionRequired.AddAnnotation("Relational:ColumnName", "Planning Record.Is planning permission required?");
            planningRecordIsPlanningPermissionRequired.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordIsThisTheMainPlanningRecord = runtimeEntityType.AddProperty(
                "PlanningRecordIsThisTheMainPlanningRecord",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordIsThisTheMainPlanningRecord", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordIsThisTheMainPlanningRecord>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            planningRecordIsThisTheMainPlanningRecord.AddAnnotation("Relational:ColumnName", "Planning Record.Is this the main planning record?");
            planningRecordIsThisTheMainPlanningRecord.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordJrChallengePeriodFinishedActual = runtimeEntityType.AddProperty(
                "PlanningRecordJrChallengePeriodFinishedActual",
                typeof(DateTime?),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordJrChallengePeriodFinishedActual", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordJrChallengePeriodFinishedActual>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            planningRecordJrChallengePeriodFinishedActual.AddAnnotation("Relational:ColumnName", "Planning Record.JR challenge period finished (actual)");
            planningRecordJrChallengePeriodFinishedActual.AddAnnotation("Relational:ColumnType", "date");
            planningRecordJrChallengePeriodFinishedActual.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordLocalPlanningAuthority = runtimeEntityType.AddProperty(
                "PlanningRecordLocalPlanningAuthority",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordLocalPlanningAuthority", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordLocalPlanningAuthority>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            planningRecordLocalPlanningAuthority.AddAnnotation("Relational:ColumnName", "Planning Record.Local planning authority");
            planningRecordLocalPlanningAuthority.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordLpaApplicationReference = runtimeEntityType.AddProperty(
                "PlanningRecordLpaApplicationReference",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordLpaApplicationReference", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordLpaApplicationReference>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            planningRecordLpaApplicationReference.AddAnnotation("Relational:ColumnName", "Planning Record.LPA application reference");
            planningRecordLpaApplicationReference.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordNameManualOverwrite = runtimeEntityType.AddProperty(
                "PlanningRecordNameManualOverwrite",
                typeof(bool?),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordNameManualOverwrite", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordNameManualOverwrite>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            planningRecordNameManualOverwrite.AddAnnotation("Relational:ColumnName", "Planning Record.Name - Manual overwrite?");
            planningRecordNameManualOverwrite.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordPlanningAppraisalCompleted = runtimeEntityType.AddProperty(
                "PlanningRecordPlanningAppraisalCompleted",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordPlanningAppraisalCompleted", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordPlanningAppraisalCompleted>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            planningRecordPlanningAppraisalCompleted.AddAnnotation("Relational:ColumnName", "Planning Record.Planning appraisal completed");
            planningRecordPlanningAppraisalCompleted.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordPlanningDecision = runtimeEntityType.AddProperty(
                "PlanningRecordPlanningDecision",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordPlanningDecision", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordPlanningDecision>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            planningRecordPlanningDecision.AddAnnotation("Relational:ColumnName", "Planning Record.Planning decision");
            planningRecordPlanningDecision.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordPlanningLeadComments = runtimeEntityType.AddProperty(
                "PlanningRecordPlanningLeadComments",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordPlanningLeadComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordPlanningLeadComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 999,
                unicode: false);
            planningRecordPlanningLeadComments.AddAnnotation("Relational:ColumnName", "Planning Record.Planning Lead comments");
            planningRecordPlanningLeadComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordPlanningPermissionLimitedToASpecificTimeAndExpiryPeriod = runtimeEntityType.AddProperty(
                "PlanningRecordPlanningPermissionLimitedToASpecificTimeAndExpiryPeriod",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordPlanningPermissionLimitedToASpecificTimeAndExpiryPeriod", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordPlanningPermissionLimitedToASpecificTimeAndExpiryPeriod>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            planningRecordPlanningPermissionLimitedToASpecificTimeAndExpiryPeriod.AddAnnotation("Relational:ColumnName", "Planning Record.Planning permission limited to a specific time and expiry period");
            planningRecordPlanningPermissionLimitedToASpecificTimeAndExpiryPeriod.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordPlanningRisk = runtimeEntityType.AddProperty(
                "PlanningRecordPlanningRisk",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordPlanningRisk", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordPlanningRisk>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            planningRecordPlanningRisk.AddAnnotation("Relational:ColumnName", "Planning Record.Planning risk");
            planningRecordPlanningRisk.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordPostcodeManualOverwrite = runtimeEntityType.AddProperty(
                "PlanningRecordPostcodeManualOverwrite",
                typeof(bool?),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordPostcodeManualOverwrite", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordPostcodeManualOverwrite>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            planningRecordPostcodeManualOverwrite.AddAnnotation("Relational:ColumnName", "Planning Record.Postcode - Manual overwrite?");
            planningRecordPostcodeManualOverwrite.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordPostcodeOfSite = runtimeEntityType.AddProperty(
                "PlanningRecordPostcodeOfSite",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordPostcodeOfSite", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordPostcodeOfSite>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            planningRecordPostcodeOfSite.AddAnnotation("Relational:ColumnName", "Planning Record.Postcode of site");
            planningRecordPostcodeOfSite.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordPrNameOfSite = runtimeEntityType.AddProperty(
                "PlanningRecordPrNameOfSite",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordPrNameOfSite", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordPrNameOfSite>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            planningRecordPrNameOfSite.AddAnnotation("Relational:ColumnName", "Planning Record.PR_Name of site");
            planningRecordPrNameOfSite.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordPrPlanningPermissionExpiryDateActual = runtimeEntityType.AddProperty(
                "PlanningRecordPrPlanningPermissionExpiryDateActual",
                typeof(DateTime?),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordPrPlanningPermissionExpiryDateActual", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordPrPlanningPermissionExpiryDateActual>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            planningRecordPrPlanningPermissionExpiryDateActual.AddAnnotation("Relational:ColumnName", "Planning Record.PR_Planning permission expiry date (actual)");
            planningRecordPrPlanningPermissionExpiryDateActual.AddAnnotation("Relational:ColumnType", "date");
            planningRecordPrPlanningPermissionExpiryDateActual.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordSiteId = runtimeEntityType.AddProperty(
                "PlanningRecordSiteId",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordSiteId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordSiteId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            planningRecordSiteId.AddAnnotation("Relational:ColumnName", "Planning Record.Site ID");
            planningRecordSiteId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordStorePlanningRecordId = runtimeEntityType.AddProperty(
                "PlanningRecordStorePlanningRecordId",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordStorePlanningRecordId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordStorePlanningRecordId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            planningRecordStorePlanningRecordId.AddAnnotation("Relational:ColumnName", "Planning Record.Store planning record ID");
            planningRecordStorePlanningRecordId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordTypeOfPlanningRequired = runtimeEntityType.AddProperty(
                "PlanningRecordTypeOfPlanningRequired",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordTypeOfPlanningRequired", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordTypeOfPlanningRequired>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 1000,
                unicode: false);
            planningRecordTypeOfPlanningRequired.AddAnnotation("Relational:ColumnName", "Planning Record.Type of planning required");
            planningRecordTypeOfPlanningRequired.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var planningRecordWasPlanningSecuredInTimeForSchoolRequirements = runtimeEntityType.AddProperty(
                "PlanningRecordWasPlanningSecuredInTimeForSchoolRequirements",
                typeof(string),
                propertyInfo: typeof(Planning).GetProperty("PlanningRecordWasPlanningSecuredInTimeForSchoolRequirements", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Planning).GetField("<PlanningRecordWasPlanningSecuredInTimeForSchoolRequirements>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            planningRecordWasPlanningSecuredInTimeForSchoolRequirements.AddAnnotation("Relational:ColumnName", "Planning Record.Was planning secured in time for school requirements?");
            planningRecordWasPlanningSecuredInTimeForSchoolRequirements.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { rid });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "dbo");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Planning");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);
            runtimeEntityType.AddAnnotation("SqlServer:IsTemporal", true);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
