// <auto-generated />
using System;
using System.Reflection;
using Dfe.ManageFreeSchoolProjects.Data.Entities.Existing;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Dfe.ManageFreeSchoolProjects.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class PorfEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Dfe.ManageFreeSchoolProjects.Data.Entities.Existing.Porf",
                typeof(Porf),
                baseEntityType,
                propertyCount: 11,
                keyCount: 1);

            var rid = runtimeEntityType.AddProperty(
                "Rid",
                typeof(string),
                propertyInfo: typeof(Porf).GetProperty("Rid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Porf).GetField("<Rid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 11,
                unicode: false);
            rid.AddAnnotation("Relational:ColumnName", "RID");
            rid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var pRid = runtimeEntityType.AddProperty(
                "PRid",
                typeof(string),
                propertyInfo: typeof(Porf).GetProperty("PRid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Porf).GetField("<PRid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 11,
                unicode: false);
            pRid.AddAnnotation("Relational:ColumnName", "p_rid");
            pRid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var periodEnd = runtimeEntityType.AddProperty(
                "PeriodEnd",
                typeof(DateTime),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            periodEnd.AddAnnotation("Relational:ColumnName", "PeriodEnd");
            periodEnd.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var periodStart = runtimeEntityType.AddProperty(
                "PeriodStart",
                typeof(DateTime),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            periodStart.AddAnnotation("Relational:ColumnName", "PeriodStart");
            periodStart.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var purchaseOrderRequestFormPorfGlCode = runtimeEntityType.AddProperty(
                "PurchaseOrderRequestFormPorfGlCode",
                typeof(string),
                propertyInfo: typeof(Porf).GetProperty("PurchaseOrderRequestFormPorfGlCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Porf).GetField("<PurchaseOrderRequestFormPorfGlCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            purchaseOrderRequestFormPorfGlCode.AddAnnotation("Relational:ColumnName", "Purchase Order Request Form.PORF GL code");
            purchaseOrderRequestFormPorfGlCode.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var purchaseOrderRequestFormPorfId = runtimeEntityType.AddProperty(
                "PurchaseOrderRequestFormPorfId",
                typeof(string),
                propertyInfo: typeof(Porf).GetProperty("PurchaseOrderRequestFormPorfId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Porf).GetField("<PurchaseOrderRequestFormPorfId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            purchaseOrderRequestFormPorfId.AddAnnotation("Relational:ColumnName", "Purchase Order Request Form.PORF ID");
            purchaseOrderRequestFormPorfId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var purchaseOrderRequestFormPurchaseOrderCreatedDate = runtimeEntityType.AddProperty(
                "PurchaseOrderRequestFormPurchaseOrderCreatedDate",
                typeof(DateTime?),
                propertyInfo: typeof(Porf).GetProperty("PurchaseOrderRequestFormPurchaseOrderCreatedDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Porf).GetField("<PurchaseOrderRequestFormPurchaseOrderCreatedDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            purchaseOrderRequestFormPurchaseOrderCreatedDate.AddAnnotation("Relational:ColumnName", "Purchase Order Request Form.Purchase Order created date");
            purchaseOrderRequestFormPurchaseOrderCreatedDate.AddAnnotation("Relational:ColumnType", "date");
            purchaseOrderRequestFormPurchaseOrderCreatedDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var purchaseOrderRequestFormPurchaseOrderNumber = runtimeEntityType.AddProperty(
                "PurchaseOrderRequestFormPurchaseOrderNumber",
                typeof(string),
                propertyInfo: typeof(Porf).GetProperty("PurchaseOrderRequestFormPurchaseOrderNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Porf).GetField("<PurchaseOrderRequestFormPurchaseOrderNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            purchaseOrderRequestFormPurchaseOrderNumber.AddAnnotation("Relational:ColumnName", "Purchase Order Request Form.Purchase Order number");
            purchaseOrderRequestFormPurchaseOrderNumber.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var purchaseOrderRequestFormPurchaseOrderRequestFormTotalValueExclVat = runtimeEntityType.AddProperty(
                "PurchaseOrderRequestFormPurchaseOrderRequestFormTotalValueExclVat",
                typeof(string),
                propertyInfo: typeof(Porf).GetProperty("PurchaseOrderRequestFormPurchaseOrderRequestFormTotalValueExclVat", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Porf).GetField("<PurchaseOrderRequestFormPurchaseOrderRequestFormTotalValueExclVat>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            purchaseOrderRequestFormPurchaseOrderRequestFormTotalValueExclVat.AddAnnotation("Relational:ColumnName", "Purchase Order Request Form.Purchase Order Request Form Total value (excl VAT)");
            purchaseOrderRequestFormPurchaseOrderRequestFormTotalValueExclVat.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var purchaseOrderRequestFormPurchaseOrderRequestFormVat = runtimeEntityType.AddProperty(
                "PurchaseOrderRequestFormPurchaseOrderRequestFormVat",
                typeof(string),
                propertyInfo: typeof(Porf).GetProperty("PurchaseOrderRequestFormPurchaseOrderRequestFormVat", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Porf).GetField("<PurchaseOrderRequestFormPurchaseOrderRequestFormVat>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            purchaseOrderRequestFormPurchaseOrderRequestFormVat.AddAnnotation("Relational:ColumnName", "Purchase Order Request Form.Purchase Order Request Form VAT");
            purchaseOrderRequestFormPurchaseOrderRequestFormVat.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var purchaseOrderRequestFormPurchaseOrderRequestFormVendor = runtimeEntityType.AddProperty(
                "PurchaseOrderRequestFormPurchaseOrderRequestFormVendor",
                typeof(string),
                propertyInfo: typeof(Porf).GetProperty("PurchaseOrderRequestFormPurchaseOrderRequestFormVendor", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Porf).GetField("<PurchaseOrderRequestFormPurchaseOrderRequestFormVendor>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            purchaseOrderRequestFormPurchaseOrderRequestFormVendor.AddAnnotation("Relational:ColumnName", "Purchase Order Request Form.Purchase Order Request Form - Vendor");
            purchaseOrderRequestFormPurchaseOrderRequestFormVendor.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { rid });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "dbo");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "PORF");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);
            runtimeEntityType.AddAnnotation("SqlServer:IsTemporal", true);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
