// <auto-generated />
using System;
using System.Reflection;
using Dfe.ManageFreeSchoolProjects.Data.Entities.Existing;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Dfe.ManageFreeSchoolProjects.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class PropertyQaEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Dfe.ManageFreeSchoolProjects.Data.Entities.Existing.PropertyQa",
                typeof(PropertyQa),
                baseEntityType,
                propertyCount: 22);

            var addressOfSite = runtimeEntityType.AddProperty(
                "AddressOfSite",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("AddressOfSite", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<AddressOfSite>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            addressOfSite.AddAnnotation("Relational:ColumnName", "Address of site");
            addressOfSite.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var dateOfCompletionForecast = runtimeEntityType.AddProperty(
                "DateOfCompletionForecast",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("DateOfCompletionForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<DateOfCompletionForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            dateOfCompletionForecast.AddAnnotation("Relational:ColumnName", "Date of completion (forecast)");
            dateOfCompletionForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var dateOfExchangeActual = runtimeEntityType.AddProperty(
                "DateOfExchangeActual",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("DateOfExchangeActual", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<DateOfExchangeActual>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            dateOfExchangeActual.AddAnnotation("Relational:ColumnName", "Date of exchange (actual)");
            dateOfExchangeActual.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var dateOfExchangeForecast = runtimeEntityType.AddProperty(
                "DateOfExchangeForecast",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("DateOfExchangeForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<DateOfExchangeForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            dateOfExchangeForecast.AddAnnotation("Relational:ColumnName", "Date of exchange (forecast)");
            dateOfExchangeForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var dateOfHeadsOfTermsAgreedActual = runtimeEntityType.AddProperty(
                "DateOfHeadsOfTermsAgreedActual",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("DateOfHeadsOfTermsAgreedActual", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<DateOfHeadsOfTermsAgreedActual>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            dateOfHeadsOfTermsAgreedActual.AddAnnotation("Relational:ColumnName", "Date of heads of terms agreed (actual)");
            dateOfHeadsOfTermsAgreedActual.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var dateOfHeadsOfTermsAgreedForecast = runtimeEntityType.AddProperty(
                "DateOfHeadsOfTermsAgreedForecast",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("DateOfHeadsOfTermsAgreedForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<DateOfHeadsOfTermsAgreedForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            dateOfHeadsOfTermsAgreedForecast.AddAnnotation("Relational:ColumnName", "Date of heads of terms agreed (forecast)");
            dateOfHeadsOfTermsAgreedForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var esfaCapitalProjectManager = runtimeEntityType.AddProperty(
                "EsfaCapitalProjectManager",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("EsfaCapitalProjectManager", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<EsfaCapitalProjectManager>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            esfaCapitalProjectManager.AddAnnotation("Relational:ColumnName", "ESFA Capital project manager");
            esfaCapitalProjectManager.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var esfaPropertyLead = runtimeEntityType.AddProperty(
                "EsfaPropertyLead",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("EsfaPropertyLead", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<EsfaPropertyLead>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            esfaPropertyLead.AddAnnotation("Relational:ColumnName", "ESFA property lead");
            esfaPropertyLead.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var esfaRegionalPropertyLead = runtimeEntityType.AddProperty(
                "EsfaRegionalPropertyLead",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("EsfaRegionalPropertyLead", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<EsfaRegionalPropertyLead>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            esfaRegionalPropertyLead.AddAnnotation("Relational:ColumnName", "ESFA regional property lead");
            esfaRegionalPropertyLead.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var headOfRegion = runtimeEntityType.AddProperty(
                "HeadOfRegion",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("HeadOfRegion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<HeadOfRegion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            headOfRegion.AddAnnotation("Relational:ColumnName", "Head of Region");
            headOfRegion.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var legalManager = runtimeEntityType.AddProperty(
                "LegalManager",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("LegalManager", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<LegalManager>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            legalManager.AddAnnotation("Relational:ColumnName", "Legal manager");
            legalManager.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var locatEdAcquisitionManager = runtimeEntityType.AddProperty(
                "LocatEdAcquisitionManager",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("LocatEdAcquisitionManager", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<LocatEdAcquisitionManager>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            locatEdAcquisitionManager.AddAnnotation("Relational:ColumnName", "LocatED acquisition manager");
            locatEdAcquisitionManager.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var locatEdCommissionReference = runtimeEntityType.AddProperty(
                "LocatEdCommissionReference",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("LocatEdCommissionReference", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<LocatEdCommissionReference>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            locatEdCommissionReference.AddAnnotation("Relational:ColumnName", "LocatED commission reference");
            locatEdCommissionReference.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var locatEdDelivery = runtimeEntityType.AddProperty(
                "LocatEdDelivery",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("LocatEdDelivery", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<LocatEdDelivery>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            locatEdDelivery.AddAnnotation("Relational:ColumnName", "LocatED delivery");
            locatEdDelivery.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var month = runtimeEntityType.AddProperty(
                "Month",
                typeof(string),
                propertyInfo: typeof(PropertyQa).GetProperty("Month", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<Month>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            month.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var nameOfSite = runtimeEntityType.AddProperty(
                "NameOfSite",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("NameOfSite", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<NameOfSite>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            nameOfSite.AddAnnotation("Relational:ColumnName", "Name of site");
            nameOfSite.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var pleaseStateReasonIfMoreThanOneTenureTypeSelected = runtimeEntityType.AddProperty(
                "PleaseStateReasonIfMoreThanOneTenureTypeSelected",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("PleaseStateReasonIfMoreThanOneTenureTypeSelected", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<PleaseStateReasonIfMoreThanOneTenureTypeSelected>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            pleaseStateReasonIfMoreThanOneTenureTypeSelected.AddAnnotation("Relational:ColumnName", "Please state reason if more than one tenure type selected");
            pleaseStateReasonIfMoreThanOneTenureTypeSelected.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var postcodeOfSite = runtimeEntityType.AddProperty(
                "PostcodeOfSite",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("PostcodeOfSite", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<PostcodeOfSite>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            postcodeOfSite.AddAnnotation("Relational:ColumnName", "Postcode of site");
            postcodeOfSite.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var projectDirector = runtimeEntityType.AddProperty(
                "ProjectDirector",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("ProjectDirector", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<ProjectDirector>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            projectDirector.AddAnnotation("Relational:ColumnName", "Project director");
            projectDirector.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var siteIdentifiedActual = runtimeEntityType.AddProperty(
                "SiteIdentifiedActual",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("SiteIdentifiedActual", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<SiteIdentifiedActual>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            siteIdentifiedActual.AddAnnotation("Relational:ColumnName", "Site identified (actual)");
            siteIdentifiedActual.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var siteIdentifiedForecast = runtimeEntityType.AddProperty(
                "SiteIdentifiedForecast",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("SiteIdentifiedForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<SiteIdentifiedForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            siteIdentifiedForecast.AddAnnotation("Relational:ColumnName", "Site identified (forecast)");
            siteIdentifiedForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var tenureHighlight = runtimeEntityType.AddProperty(
                "TenureHighlight",
                typeof(int),
                propertyInfo: typeof(PropertyQa).GetProperty("TenureHighlight", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PropertyQa).GetField("<TenureHighlight>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            tenureHighlight.AddAnnotation("Relational:ColumnName", "Tenure highlight");
            tenureHighlight.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "dbo");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Property_QA");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
