// <auto-generated />
using System;
using System.Reflection;
using Dfe.ManageFreeSchoolProjects.Data.Entities;
using Dfe.ManageFreeSchoolProjects.Data.Entities.Existing;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Dfe.ManageFreeSchoolProjects.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class RagEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Dfe.ManageFreeSchoolProjects.Data.Entities.Existing.Rag",
                typeof(Rag),
                baseEntityType,
                propertyCount: 42,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var rid = runtimeEntityType.AddProperty(
                "Rid",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("Rid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<Rid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 11,
                unicode: false);
            rid.AddAnnotation("Relational:ColumnName", "RID");
            rid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var pRid = runtimeEntityType.AddProperty(
                "PRid",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("PRid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<PRid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 11,
                unicode: false);
            pRid.AddAnnotation("Relational:ColumnName", "p_rid");
            pRid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var periodEnd = runtimeEntityType.AddProperty(
                "PeriodEnd",
                typeof(DateTime),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            periodEnd.AddAnnotation("Relational:ColumnName", "PeriodEnd");
            periodEnd.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var periodStart = runtimeEntityType.AddProperty(
                "PeriodStart",
                typeof(DateTime),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            periodStart.AddAnnotation("Relational:ColumnName", "PeriodStart");
            periodStart.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsAllAssessmentConditionsMet = runtimeEntityType.AddProperty(
                "RagRatingsAllAssessmentConditionsMet",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsAllAssessmentConditionsMet", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsAllAssessmentConditionsMet>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsAllAssessmentConditionsMet.AddAnnotation("Relational:ColumnName", "Rag Ratings.All assessment conditions met");
            ragRatingsAllAssessmentConditionsMet.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsAssessmentCondition1 = runtimeEntityType.AddProperty(
                "RagRatingsAssessmentCondition1",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsAssessmentCondition1", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsAssessmentCondition1>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsAssessmentCondition1.AddAnnotation("Relational:ColumnName", "Rag Ratings.Assessment condition 1");
            ragRatingsAssessmentCondition1.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsAssessmentCondition2 = runtimeEntityType.AddProperty(
                "RagRatingsAssessmentCondition2",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsAssessmentCondition2", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsAssessmentCondition2>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsAssessmentCondition2.AddAnnotation("Relational:ColumnName", "Rag Ratings.Assessment condition 2");
            ragRatingsAssessmentCondition2.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsAssessmentCondition3 = runtimeEntityType.AddProperty(
                "RagRatingsAssessmentCondition3",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsAssessmentCondition3", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsAssessmentCondition3>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsAssessmentCondition3.AddAnnotation("Relational:ColumnName", "Rag Ratings.Assessment condition 3");
            ragRatingsAssessmentCondition3.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsAssessmentCondition4 = runtimeEntityType.AddProperty(
                "RagRatingsAssessmentCondition4",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsAssessmentCondition4", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsAssessmentCondition4>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsAssessmentCondition4.AddAnnotation("Relational:ColumnName", "Rag Ratings.Assessment condition 4");
            ragRatingsAssessmentCondition4.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsAssessmentCondition5 = runtimeEntityType.AddProperty(
                "RagRatingsAssessmentCondition5",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsAssessmentCondition5", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsAssessmentCondition5>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsAssessmentCondition5.AddAnnotation("Relational:ColumnName", "Rag Ratings.Assessment condition 5");
            ragRatingsAssessmentCondition5.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsAssessmentCondition6 = runtimeEntityType.AddProperty(
                "RagRatingsAssessmentCondition6",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsAssessmentCondition6", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsAssessmentCondition6>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsAssessmentCondition6.AddAnnotation("Relational:ColumnName", "Rag Ratings.Assessment condition 6");
            ragRatingsAssessmentCondition6.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsAssessmentCondition7 = runtimeEntityType.AddProperty(
                "RagRatingsAssessmentCondition7",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsAssessmentCondition7", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsAssessmentCondition7>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsAssessmentCondition7.AddAnnotation("Relational:ColumnName", "Rag Ratings.Assessment condition 7");
            ragRatingsAssessmentCondition7.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsAssessmentCondition8 = runtimeEntityType.AddProperty(
                "RagRatingsAssessmentCondition8",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsAssessmentCondition8", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsAssessmentCondition8>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsAssessmentCondition8.AddAnnotation("Relational:ColumnName", "Rag Ratings.Assessment condition 8");
            ragRatingsAssessmentCondition8.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsEducationRag = runtimeEntityType.AddProperty(
                "RagRatingsEducationRag",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsEducationRag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsEducationRag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsEducationRag.AddAnnotation("Relational:ColumnName", "Rag Ratings.Education RAG");
            ragRatingsEducationRag.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsEducationRagSummary = runtimeEntityType.AddProperty(
                "RagRatingsEducationRagSummary",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsEducationRagSummary", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsEducationRagSummary>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 1000,
                unicode: false);
            ragRatingsEducationRagSummary.AddAnnotation("Relational:ColumnName", "Rag Ratings.Education RAG summary");
            ragRatingsEducationRagSummary.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsFinanceRagSummary = runtimeEntityType.AddProperty(
                "RagRatingsFinanceRagSummary",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsFinanceRagSummary", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsFinanceRagSummary>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 1000,
                unicode: false);
            ragRatingsFinanceRagSummary.AddAnnotation("Relational:ColumnName", "Rag Ratings.Finance RAG summary");
            ragRatingsFinanceRagSummary.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsFinancesRagRating = runtimeEntityType.AddProperty(
                "RagRatingsFinancesRagRating",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsFinancesRagRating", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsFinancesRagRating>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 1000,
                unicode: false);
            ragRatingsFinancesRagRating.AddAnnotation("Relational:ColumnName", "Rag Ratings.Finances RAG rating");
            ragRatingsFinancesRagRating.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsGovernanceAndSuitabilityRagRating = runtimeEntityType.AddProperty(
                "RagRatingsGovernanceAndSuitabilityRagRating",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsGovernanceAndSuitabilityRagRating", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsGovernanceAndSuitabilityRagRating>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsGovernanceAndSuitabilityRagRating.AddAnnotation("Relational:ColumnName", "Rag Ratings.Governance and Suitability RAG rating");
            ragRatingsGovernanceAndSuitabilityRagRating.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsGovernanceAndSuitabilityRagSummary = runtimeEntityType.AddProperty(
                "RagRatingsGovernanceAndSuitabilityRagSummary",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsGovernanceAndSuitabilityRagSummary", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsGovernanceAndSuitabilityRagSummary>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 1000,
                unicode: false);
            ragRatingsGovernanceAndSuitabilityRagSummary.AddAnnotation("Relational:ColumnName", "Rag Ratings.Governance and Suitability RAG summary");
            ragRatingsGovernanceAndSuitabilityRagSummary.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsHasCondition1BeenMet = runtimeEntityType.AddProperty(
                "RagRatingsHasCondition1BeenMet",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsHasCondition1BeenMet", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsHasCondition1BeenMet>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 1000,
                unicode: false);
            ragRatingsHasCondition1BeenMet.AddAnnotation("Relational:ColumnName", "Rag Ratings.Has condition 1 been met?");
            ragRatingsHasCondition1BeenMet.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsHasCondition2BeenMet = runtimeEntityType.AddProperty(
                "RagRatingsHasCondition2BeenMet",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsHasCondition2BeenMet", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsHasCondition2BeenMet>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsHasCondition2BeenMet.AddAnnotation("Relational:ColumnName", "Rag Ratings.Has condition 2 been met?");
            ragRatingsHasCondition2BeenMet.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsHasCondition3BeenMet = runtimeEntityType.AddProperty(
                "RagRatingsHasCondition3BeenMet",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsHasCondition3BeenMet", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsHasCondition3BeenMet>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsHasCondition3BeenMet.AddAnnotation("Relational:ColumnName", "Rag Ratings.Has condition 3 been met?");
            ragRatingsHasCondition3BeenMet.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsHasCondition4BeenMet = runtimeEntityType.AddProperty(
                "RagRatingsHasCondition4BeenMet",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsHasCondition4BeenMet", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsHasCondition4BeenMet>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsHasCondition4BeenMet.AddAnnotation("Relational:ColumnName", "Rag Ratings.Has condition 4 been met?");
            ragRatingsHasCondition4BeenMet.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsHasCondition5BeenMet = runtimeEntityType.AddProperty(
                "RagRatingsHasCondition5BeenMet",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsHasCondition5BeenMet", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsHasCondition5BeenMet>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsHasCondition5BeenMet.AddAnnotation("Relational:ColumnName", "Rag Ratings.Has condition 5 been met?");
            ragRatingsHasCondition5BeenMet.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsHasCondition6BeenMet = runtimeEntityType.AddProperty(
                "RagRatingsHasCondition6BeenMet",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsHasCondition6BeenMet", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsHasCondition6BeenMet>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsHasCondition6BeenMet.AddAnnotation("Relational:ColumnName", "Rag Ratings.Has condition 6 been met?");
            ragRatingsHasCondition6BeenMet.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsHasCondition7BeenMet = runtimeEntityType.AddProperty(
                "RagRatingsHasCondition7BeenMet",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsHasCondition7BeenMet", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsHasCondition7BeenMet>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsHasCondition7BeenMet.AddAnnotation("Relational:ColumnName", "Rag Ratings.Has condition 7 been met?");
            ragRatingsHasCondition7BeenMet.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsHasCondition8BeenMet = runtimeEntityType.AddProperty(
                "RagRatingsHasCondition8BeenMet",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsHasCondition8BeenMet", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsHasCondition8BeenMet>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsHasCondition8BeenMet.AddAnnotation("Relational:ColumnName", "Rag Ratings.Has condition 8 been met?");
            ragRatingsHasCondition8BeenMet.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsInclusivityIssue = runtimeEntityType.AddProperty(
                "RagRatingsInclusivityIssue",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsInclusivityIssue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsInclusivityIssue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsInclusivityIssue.AddAnnotation("Relational:ColumnName", "Rag Ratings.Inclusivity Issue");
            ragRatingsInclusivityIssue.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsLinkToRiskAssessmentMatrix = runtimeEntityType.AddProperty(
                "RagRatingsLinkToRiskAssessmentMatrix",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsLinkToRiskAssessmentMatrix", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsLinkToRiskAssessmentMatrix>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsLinkToRiskAssessmentMatrix.AddAnnotation("Relational:ColumnName", "Rag Ratings.Link to Risk Assessment Matrix");
            ragRatingsLinkToRiskAssessmentMatrix.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsLocalContextRagRating = runtimeEntityType.AddProperty(
                "RagRatingsLocalContextRagRating",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsLocalContextRagRating", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsLocalContextRagRating>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsLocalContextRagRating.AddAnnotation("Relational:ColumnName", "Rag Ratings.Local context RAG rating");
            ragRatingsLocalContextRagRating.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsOverallRagRating = runtimeEntityType.AddProperty(
                "RagRatingsOverallRagRating",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsOverallRagRating", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsOverallRagRating>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsOverallRagRating.AddAnnotation("Relational:ColumnName", "Rag Ratings.Overall RAG rating");
            ragRatingsOverallRagRating.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsOverallRagSummary = runtimeEntityType.AddProperty(
                "RagRatingsOverallRagSummary",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsOverallRagSummary", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsOverallRagSummary>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 5000,
                unicode: false);
            ragRatingsOverallRagSummary.AddAnnotation("Relational:ColumnName", "Rag Ratings.Overall RAG summary");
            ragRatingsOverallRagSummary.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsOverallRomRagRating = runtimeEntityType.AddProperty(
                "RagRatingsOverallRomRagRating",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsOverallRomRagRating", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsOverallRomRagRating>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsOverallRomRagRating.AddAnnotation("Relational:ColumnName", "Rag Ratings.Overall ROM RAG rating");
            ragRatingsOverallRomRagRating.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsPipelineFreeSchoolsJointRiskCategory = runtimeEntityType.AddProperty(
                "RagRatingsPipelineFreeSchoolsJointRiskCategory",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsPipelineFreeSchoolsJointRiskCategory", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsPipelineFreeSchoolsJointRiskCategory>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsPipelineFreeSchoolsJointRiskCategory.AddAnnotation("Relational:ColumnName", "Rag Ratings.Pipeline Free Schools Joint Risk Category");
            ragRatingsPipelineFreeSchoolsJointRiskCategory.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsProjectRecommendation = runtimeEntityType.AddProperty(
                "RagRatingsProjectRecommendation",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsProjectRecommendation", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsProjectRecommendation>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsProjectRecommendation.AddAnnotation("Relational:ColumnName", "Rag Ratings.Project recommendation");
            ragRatingsProjectRecommendation.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsPupilRecruitmentRagRating = runtimeEntityType.AddProperty(
                "RagRatingsPupilRecruitmentRagRating",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsPupilRecruitmentRagRating", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsPupilRecruitmentRagRating>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsPupilRecruitmentRagRating.AddAnnotation("Relational:ColumnName", "Rag Ratings.Pupil recruitment RAG rating");
            ragRatingsPupilRecruitmentRagRating.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsReasonForJointRiskCategory = runtimeEntityType.AddProperty(
                "RagRatingsReasonForJointRiskCategory",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsReasonForJointRiskCategory", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsReasonForJointRiskCategory>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ragRatingsReasonForJointRiskCategory.AddAnnotation("Relational:ColumnName", "Rag Ratings.Reason for Joint Risk Category");
            ragRatingsReasonForJointRiskCategory.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsRiskAppraisalFormSharepointLink = runtimeEntityType.AddProperty(
                "RagRatingsRiskAppraisalFormSharepointLink",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsRiskAppraisalFormSharepointLink", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsRiskAppraisalFormSharepointLink>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500,
                unicode: false);
            ragRatingsRiskAppraisalFormSharepointLink.AddAnnotation("Relational:ColumnName", "Rag Ratings.Risk Appraisal Form Sharepoint Link");
            ragRatingsRiskAppraisalFormSharepointLink.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsRscStocktakeRecommendationSummary = runtimeEntityType.AddProperty(
                "RagRatingsRscStocktakeRecommendationSummary",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsRscStocktakeRecommendationSummary", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsRscStocktakeRecommendationSummary>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 1000,
                unicode: false);
            ragRatingsRscStocktakeRecommendationSummary.AddAnnotation("Relational:ColumnName", "Rag Ratings.RSC stocktake recommendation summary");
            ragRatingsRscStocktakeRecommendationSummary.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ragRatingsSummaryOfInclusivityIssue = runtimeEntityType.AddProperty(
                "RagRatingsSummaryOfInclusivityIssue",
                typeof(string),
                propertyInfo: typeof(Rag).GetProperty("RagRatingsSummaryOfInclusivityIssue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RagRatingsSummaryOfInclusivityIssue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 999,
                unicode: false);
            ragRatingsSummaryOfInclusivityIssue.AddAnnotation("Relational:ColumnName", "Rag Ratings.Summary of inclusivity issue");
            ragRatingsSummaryOfInclusivityIssue.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var revisionMarker = runtimeEntityType.AddProperty(
                "RevisionMarker",
                typeof(Guid),
                propertyInfo: typeof(Rag).GetProperty("RevisionMarker", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rag).GetField("<RevisionMarker>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            revisionMarker.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var updatedByUserId = runtimeEntityType.AddProperty(
                "UpdatedByUserId",
                typeof(int?),
                propertyInfo: typeof(IAuditable).GetProperty("UpdatedByUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IAuditable).GetField("<UpdatedByUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            updatedByUserId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { rid });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { updatedByUserId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UpdatedByUserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "dbo");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "RAG");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);
            runtimeEntityType.AddAnnotation("SqlServer:IsTemporal", true);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
