// <auto-generated />
using System;
using System.Reflection;
using Dfe.ManageFreeSchoolProjects.Data.Entities.Existing;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Dfe.ManageFreeSchoolProjects.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class RagtempBudgetEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Dfe.ManageFreeSchoolProjects.Data.Entities.Existing.RagtempBudget",
                typeof(RagtempBudget),
                baseEntityType,
                propertyCount: 59);

            var constructionCostsInclPassiveIctPlanningObligationsExclVatCostToDate = runtimeEntityType.AddProperty(
                "ConstructionCostsInclPassiveIctPlanningObligationsExclVatCostToDate",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("ConstructionCostsInclPassiveIctPlanningObligationsExclVatCostToDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<ConstructionCostsInclPassiveIctPlanningObligationsExclVatCostToDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            constructionCostsInclPassiveIctPlanningObligationsExclVatCostToDate.AddAnnotation("Relational:ColumnName", "Construction Costs (incl passive ICT / Planning Obligations) excl VAT Cost to date");
            constructionCostsInclPassiveIctPlanningObligationsExclVatCostToDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var constructionCostsInclPassiveIctPlanningObligationsExclVatForecast = runtimeEntityType.AddProperty(
                "ConstructionCostsInclPassiveIctPlanningObligationsExclVatForecast",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("ConstructionCostsInclPassiveIctPlanningObligationsExclVatForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<ConstructionCostsInclPassiveIctPlanningObligationsExclVatForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            constructionCostsInclPassiveIctPlanningObligationsExclVatForecast.AddAnnotation("Relational:ColumnName", "Construction Costs (incl passive ICT / Planning Obligations) excl VAT Forecast");
            constructionCostsInclPassiveIctPlanningObligationsExclVatForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ffEExclVatCostToDate = runtimeEntityType.AddProperty(
                "FfEExclVatCostToDate",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("FfEExclVatCostToDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<FfEExclVatCostToDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ffEExclVatCostToDate.AddAnnotation("Relational:ColumnName", "FF & E (excl VAT) Cost to date");
            ffEExclVatCostToDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ffEExclVatForecast = runtimeEntityType.AddProperty(
                "FfEExclVatForecast",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("FfEExclVatForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<FfEExclVatForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ffEExclVatForecast.AddAnnotation("Relational:ColumnName", "FF & E (excl VAT) Forecast");
            ffEExclVatForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fscode = runtimeEntityType.AddProperty(
                "Fscode",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("Fscode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<Fscode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            fscode.AddAnnotation("Relational:ColumnName", "FSCode");
            fscode.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ictActivesExclVatCostToDate = runtimeEntityType.AddProperty(
                "IctActivesExclVatCostToDate",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("IctActivesExclVatCostToDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<IctActivesExclVatCostToDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ictActivesExclVatCostToDate.AddAnnotation("Relational:ColumnName", "ICT Actives (excl VAT) Cost to date");
            ictActivesExclVatCostToDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ictActivesExclVatForecast = runtimeEntityType.AddProperty(
                "IctActivesExclVatForecast",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("IctActivesExclVatForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<IctActivesExclVatForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ictActivesExclVatForecast.AddAnnotation("Relational:ColumnName", "ICT Actives (excl VAT) Forecast");
            ictActivesExclVatForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ictBroadbandExclVatCostToDate = runtimeEntityType.AddProperty(
                "IctBroadbandExclVatCostToDate",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("IctBroadbandExclVatCostToDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<IctBroadbandExclVatCostToDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ictBroadbandExclVatCostToDate.AddAnnotation("Relational:ColumnName", "ICT Broadband (excl VAT) Cost to date");
            ictBroadbandExclVatCostToDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ictBroadbandExclVatForecast = runtimeEntityType.AddProperty(
                "IctBroadbandExclVatForecast",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("IctBroadbandExclVatForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<IctBroadbandExclVatForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ictBroadbandExclVatForecast.AddAnnotation("Relational:ColumnName", "ICT Broadband (excl VAT) Forecast");
            ictBroadbandExclVatForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ictHardwareEquipmentExclVatCostToDate = runtimeEntityType.AddProperty(
                "IctHardwareEquipmentExclVatCostToDate",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("IctHardwareEquipmentExclVatCostToDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<IctHardwareEquipmentExclVatCostToDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ictHardwareEquipmentExclVatCostToDate.AddAnnotation("Relational:ColumnName", "ICT Hardware Equipment (excl VAT) Cost to date");
            ictHardwareEquipmentExclVatCostToDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ictHardwareEquipmentExclVatForecast = runtimeEntityType.AddProperty(
                "IctHardwareEquipmentExclVatForecast",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("IctHardwareEquipmentExclVatForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<IctHardwareEquipmentExclVatForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ictHardwareEquipmentExclVatForecast.AddAnnotation("Relational:ColumnName", "ICT Hardware Equipment (excl VAT) Forecast");
            ictHardwareEquipmentExclVatForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var legalFeesConstructionInclVatComments = runtimeEntityType.AddProperty(
                "LegalFeesConstructionInclVatComments",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("LegalFeesConstructionInclVatComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<LegalFeesConstructionInclVatComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            legalFeesConstructionInclVatComments.AddAnnotation("Relational:ColumnName", "Legal fees - construction  (incl VAT) Comments");
            legalFeesConstructionInclVatComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var legalFeesConstructionInclVatCostUptoDate = runtimeEntityType.AddProperty(
                "LegalFeesConstructionInclVatCostUptoDate",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("LegalFeesConstructionInclVatCostUptoDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<LegalFeesConstructionInclVatCostUptoDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            legalFeesConstructionInclVatCostUptoDate.AddAnnotation("Relational:ColumnName", "Legal fees - construction  (incl VAT) Cost upto date");
            legalFeesConstructionInclVatCostUptoDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var legalFeesConstructionInclVatForecast = runtimeEntityType.AddProperty(
                "LegalFeesConstructionInclVatForecast",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("LegalFeesConstructionInclVatForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<LegalFeesConstructionInclVatForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            legalFeesConstructionInclVatForecast.AddAnnotation("Relational:ColumnName", "Legal fees - construction  (incl VAT) Forecast");
            legalFeesConstructionInclVatForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var permanentBudgetRag = runtimeEntityType.AddProperty(
                "PermanentBudgetRag",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("PermanentBudgetRag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<PermanentBudgetRag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            permanentBudgetRag.AddAnnotation("Relational:ColumnName", "Permanent Budget RAG");
            permanentBudgetRag.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var permanentConstructionCostsInclPassiveIctPlanningObligationsExclVatComments = runtimeEntityType.AddProperty(
                "PermanentConstructionCostsInclPassiveIctPlanningObligationsExclVatComments",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("PermanentConstructionCostsInclPassiveIctPlanningObligationsExclVatComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<PermanentConstructionCostsInclPassiveIctPlanningObligationsExclVatComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            permanentConstructionCostsInclPassiveIctPlanningObligationsExclVatComments.AddAnnotation("Relational:ColumnName", "Permanent Construction Costs (incl passive ICT / Planning Obligations) excl VAT Comments");
            permanentConstructionCostsInclPassiveIctPlanningObligationsExclVatComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var permanentConstructionSubTotalComments = runtimeEntityType.AddProperty(
                "PermanentConstructionSubTotalComments",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("PermanentConstructionSubTotalComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<PermanentConstructionSubTotalComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            permanentConstructionSubTotalComments.AddAnnotation("Relational:ColumnName", "Permanent Construction sub total comments");
            permanentConstructionSubTotalComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var permanentFfEExclVatComments = runtimeEntityType.AddProperty(
                "PermanentFfEExclVatComments",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("PermanentFfEExclVatComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<PermanentFfEExclVatComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            permanentFfEExclVatComments.AddAnnotation("Relational:ColumnName", "Permanent FF & E (excl VAT) Comments");
            permanentFfEExclVatComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var permanentIctActivesExclVatComments = runtimeEntityType.AddProperty(
                "PermanentIctActivesExclVatComments",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("PermanentIctActivesExclVatComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<PermanentIctActivesExclVatComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            permanentIctActivesExclVatComments.AddAnnotation("Relational:ColumnName", "Permanent  ICT Actives (excl VAT) Comments");
            permanentIctActivesExclVatComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var permanentIctBroadbandExclVatComments = runtimeEntityType.AddProperty(
                "PermanentIctBroadbandExclVatComments",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("PermanentIctBroadbandExclVatComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<PermanentIctBroadbandExclVatComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            permanentIctBroadbandExclVatComments.AddAnnotation("Relational:ColumnName", "Permanent  ICT Broadband (excl VAT) Comments");
            permanentIctBroadbandExclVatComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var permanentIctDecantCostToDate = runtimeEntityType.AddProperty(
                "PermanentIctDecantCostToDate",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("PermanentIctDecantCostToDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<PermanentIctDecantCostToDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            permanentIctDecantCostToDate.AddAnnotation("Relational:ColumnName", "Permanent ICT Decant Cost to date");
            permanentIctDecantCostToDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var permanentIctDecantExclVatComments = runtimeEntityType.AddProperty(
                "PermanentIctDecantExclVatComments",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("PermanentIctDecantExclVatComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<PermanentIctDecantExclVatComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            permanentIctDecantExclVatComments.AddAnnotation("Relational:ColumnName", "Permanent ICT Decant (excl VAT) Comments");
            permanentIctDecantExclVatComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var permanentIctDecantExclVatForecast = runtimeEntityType.AddProperty(
                "PermanentIctDecantExclVatForecast",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("PermanentIctDecantExclVatForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<PermanentIctDecantExclVatForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            permanentIctDecantExclVatForecast.AddAnnotation("Relational:ColumnName", "Permanent ICT Decant (excl VAT) forecast");
            permanentIctDecantExclVatForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var permanentIctHardwareEquipmentExclVatComments = runtimeEntityType.AddProperty(
                "PermanentIctHardwareEquipmentExclVatComments",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("PermanentIctHardwareEquipmentExclVatComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<PermanentIctHardwareEquipmentExclVatComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            permanentIctHardwareEquipmentExclVatComments.AddAnnotation("Relational:ColumnName", "Permanent ICT Hardware Equipment (excl VAT) Comments");
            permanentIctHardwareEquipmentExclVatComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var permanentTaFeesInclVat = runtimeEntityType.AddProperty(
                "PermanentTaFeesInclVat",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("PermanentTaFeesInclVat", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<PermanentTaFeesInclVat>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            permanentTaFeesInclVat.AddAnnotation("Relational:ColumnName", "Permanent TA Fees (Incl VAT)");
            permanentTaFeesInclVat.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var permanentTaSurveysInclVatComments = runtimeEntityType.AddProperty(
                "PermanentTaSurveysInclVatComments",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("PermanentTaSurveysInclVatComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<PermanentTaSurveysInclVatComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            permanentTaSurveysInclVatComments.AddAnnotation("Relational:ColumnName", "Permanent TA Surveys (Incl VAT Comments");
            permanentTaSurveysInclVatComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var taFeesInclVatCostToDate = runtimeEntityType.AddProperty(
                "TaFeesInclVatCostToDate",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TaFeesInclVatCostToDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TaFeesInclVatCostToDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            taFeesInclVatCostToDate.AddAnnotation("Relational:ColumnName", "TA Fees (Incl VAT) Cost to date");
            taFeesInclVatCostToDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var taFeesInclVatForecast = runtimeEntityType.AddProperty(
                "TaFeesInclVatForecast",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TaFeesInclVatForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TaFeesInclVatForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            taFeesInclVatForecast.AddAnnotation("Relational:ColumnName", "TA Fees (Incl VAT) Forecast");
            taFeesInclVatForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var taSurveysInclVatCostToDate = runtimeEntityType.AddProperty(
                "TaSurveysInclVatCostToDate",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TaSurveysInclVatCostToDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TaSurveysInclVatCostToDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            taSurveysInclVatCostToDate.AddAnnotation("Relational:ColumnName", "TA Surveys (Incl VAT) Cost to date");
            taSurveysInclVatCostToDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var taSurveysInclVatForecast = runtimeEntityType.AddProperty(
                "TaSurveysInclVatForecast",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TaSurveysInclVatForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TaSurveysInclVatForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            taSurveysInclVatForecast.AddAnnotation("Relational:ColumnName", "TA Surveys (Incl VAT) Forecast");
            taSurveysInclVatForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryBudgetRag = runtimeEntityType.AddProperty(
                "TemporaryBudgetRag",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryBudgetRag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryBudgetRag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryBudgetRag.AddAnnotation("Relational:ColumnName", "Temporary Budget RAG");
            temporaryBudgetRag.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryConstructionCostsInclPassiveIctPlanningObligationsExclVatComments = runtimeEntityType.AddProperty(
                "TemporaryConstructionCostsInclPassiveIctPlanningObligationsExclVatComments",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryConstructionCostsInclPassiveIctPlanningObligationsExclVatComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryConstructionCostsInclPassiveIctPlanningObligationsExclVatComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryConstructionCostsInclPassiveIctPlanningObligationsExclVatComments.AddAnnotation("Relational:ColumnName", "Temporary Construction Costs (incl passive ICT / Planning Obligations) excl VAT Comments");
            temporaryConstructionCostsInclPassiveIctPlanningObligationsExclVatComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryConstructionCostsInclPassiveIctPlanningObligationsExclVatCostToDate = runtimeEntityType.AddProperty(
                "TemporaryConstructionCostsInclPassiveIctPlanningObligationsExclVatCostToDate",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryConstructionCostsInclPassiveIctPlanningObligationsExclVatCostToDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryConstructionCostsInclPassiveIctPlanningObligationsExclVatCostToDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryConstructionCostsInclPassiveIctPlanningObligationsExclVatCostToDate.AddAnnotation("Relational:ColumnName", "Temporary Construction Costs (incl passive ICT / Planning Obligations) excl VAT Cost to Date");
            temporaryConstructionCostsInclPassiveIctPlanningObligationsExclVatCostToDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryConstructionCostsInclPassiveIctPlanningObligationsExclVatForecast = runtimeEntityType.AddProperty(
                "TemporaryConstructionCostsInclPassiveIctPlanningObligationsExclVatForecast",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryConstructionCostsInclPassiveIctPlanningObligationsExclVatForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryConstructionCostsInclPassiveIctPlanningObligationsExclVatForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryConstructionCostsInclPassiveIctPlanningObligationsExclVatForecast.AddAnnotation("Relational:ColumnName", "Temporary Construction Costs (incl passive ICT / Planning Obligations) excl VAT Forecast");
            temporaryConstructionCostsInclPassiveIctPlanningObligationsExclVatForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryConstructionSubTotalComments = runtimeEntityType.AddProperty(
                "TemporaryConstructionSubTotalComments",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryConstructionSubTotalComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryConstructionSubTotalComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryConstructionSubTotalComments.AddAnnotation("Relational:ColumnName", "Temporary Construction sub total comments");
            temporaryConstructionSubTotalComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryFfEExclVatComments = runtimeEntityType.AddProperty(
                "TemporaryFfEExclVatComments",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryFfEExclVatComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryFfEExclVatComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryFfEExclVatComments.AddAnnotation("Relational:ColumnName", "Temporary FF & E (excl VAT) Comments");
            temporaryFfEExclVatComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryFfEExclVatCostToDate = runtimeEntityType.AddProperty(
                "TemporaryFfEExclVatCostToDate",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryFfEExclVatCostToDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryFfEExclVatCostToDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryFfEExclVatCostToDate.AddAnnotation("Relational:ColumnName", "Temporary FF & E (excl VAT) Cost to Date");
            temporaryFfEExclVatCostToDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryFfEExclVatForecast = runtimeEntityType.AddProperty(
                "TemporaryFfEExclVatForecast",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryFfEExclVatForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryFfEExclVatForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryFfEExclVatForecast.AddAnnotation("Relational:ColumnName", "Temporary FF & E (excl VAT) Forecast");
            temporaryFfEExclVatForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryIctActivesExclVatComments = runtimeEntityType.AddProperty(
                "TemporaryIctActivesExclVatComments",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryIctActivesExclVatComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryIctActivesExclVatComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryIctActivesExclVatComments.AddAnnotation("Relational:ColumnName", "Temporary  ICT Actives (excl VAT) Comments");
            temporaryIctActivesExclVatComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryIctActivesExclVatCostToDate = runtimeEntityType.AddProperty(
                "TemporaryIctActivesExclVatCostToDate",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryIctActivesExclVatCostToDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryIctActivesExclVatCostToDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryIctActivesExclVatCostToDate.AddAnnotation("Relational:ColumnName", "Temporary  ICT Actives (excl VAT) Cost to date");
            temporaryIctActivesExclVatCostToDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryIctActivesExclVatForecast = runtimeEntityType.AddProperty(
                "TemporaryIctActivesExclVatForecast",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryIctActivesExclVatForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryIctActivesExclVatForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryIctActivesExclVatForecast.AddAnnotation("Relational:ColumnName", "Temporary ICT Actives (excl VAT) Forecast");
            temporaryIctActivesExclVatForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryIctBroadbandExclVatComments = runtimeEntityType.AddProperty(
                "TemporaryIctBroadbandExclVatComments",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryIctBroadbandExclVatComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryIctBroadbandExclVatComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryIctBroadbandExclVatComments.AddAnnotation("Relational:ColumnName", "Temporary  ICT Broadband (excl VAT) Comments");
            temporaryIctBroadbandExclVatComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryIctBroadbandExclVatCostToDate = runtimeEntityType.AddProperty(
                "TemporaryIctBroadbandExclVatCostToDate",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryIctBroadbandExclVatCostToDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryIctBroadbandExclVatCostToDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryIctBroadbandExclVatCostToDate.AddAnnotation("Relational:ColumnName", "Temporary  ICT Broadband (excl VAT) Cost to date");
            temporaryIctBroadbandExclVatCostToDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryIctBroadbandExclVatForecast = runtimeEntityType.AddProperty(
                "TemporaryIctBroadbandExclVatForecast",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryIctBroadbandExclVatForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryIctBroadbandExclVatForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryIctBroadbandExclVatForecast.AddAnnotation("Relational:ColumnName", "Temporary  ICT Broadband (excl VAT) Forecast");
            temporaryIctBroadbandExclVatForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryIctDecantExclVatComments = runtimeEntityType.AddProperty(
                "TemporaryIctDecantExclVatComments",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryIctDecantExclVatComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryIctDecantExclVatComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryIctDecantExclVatComments.AddAnnotation("Relational:ColumnName", "Temporary  ICT Decant (excl VAT) Comments");
            temporaryIctDecantExclVatComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryIctDecantExclVatCostToDate = runtimeEntityType.AddProperty(
                "TemporaryIctDecantExclVatCostToDate",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryIctDecantExclVatCostToDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryIctDecantExclVatCostToDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryIctDecantExclVatCostToDate.AddAnnotation("Relational:ColumnName", "Temporary  ICT Decant (excl VAT) Cost to date");
            temporaryIctDecantExclVatCostToDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryIctDecantExclVatForecast = runtimeEntityType.AddProperty(
                "TemporaryIctDecantExclVatForecast",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryIctDecantExclVatForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryIctDecantExclVatForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryIctDecantExclVatForecast.AddAnnotation("Relational:ColumnName", "Temporary  ICT Decant (excl VAT) Forecast");
            temporaryIctDecantExclVatForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryIctHardwareEquipmentExclVatComments = runtimeEntityType.AddProperty(
                "TemporaryIctHardwareEquipmentExclVatComments",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryIctHardwareEquipmentExclVatComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryIctHardwareEquipmentExclVatComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryIctHardwareEquipmentExclVatComments.AddAnnotation("Relational:ColumnName", "Temporary  ICT Hardware Equipment (excl VAT) Comments");
            temporaryIctHardwareEquipmentExclVatComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryIctHardwareEquipmentExclVatCostToDate = runtimeEntityType.AddProperty(
                "TemporaryIctHardwareEquipmentExclVatCostToDate",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryIctHardwareEquipmentExclVatCostToDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryIctHardwareEquipmentExclVatCostToDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryIctHardwareEquipmentExclVatCostToDate.AddAnnotation("Relational:ColumnName", "Temporary  ICT Hardware Equipment (excl VAT) Cost to date");
            temporaryIctHardwareEquipmentExclVatCostToDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryIctHardwareEquipmentExclVatForecast = runtimeEntityType.AddProperty(
                "TemporaryIctHardwareEquipmentExclVatForecast",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryIctHardwareEquipmentExclVatForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryIctHardwareEquipmentExclVatForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryIctHardwareEquipmentExclVatForecast.AddAnnotation("Relational:ColumnName", "Temporary  ICT Hardware Equipment (excl VAT) Forecast");
            temporaryIctHardwareEquipmentExclVatForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryLegalFeesConstructionInclVatComments = runtimeEntityType.AddProperty(
                "TemporaryLegalFeesConstructionInclVatComments",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryLegalFeesConstructionInclVatComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryLegalFeesConstructionInclVatComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryLegalFeesConstructionInclVatComments.AddAnnotation("Relational:ColumnName", "Temporary Legal fees - construction  (incl VAT) Comments");
            temporaryLegalFeesConstructionInclVatComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryLegalFeesConstructionInclVatCostToDate = runtimeEntityType.AddProperty(
                "TemporaryLegalFeesConstructionInclVatCostToDate",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryLegalFeesConstructionInclVatCostToDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryLegalFeesConstructionInclVatCostToDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryLegalFeesConstructionInclVatCostToDate.AddAnnotation("Relational:ColumnName", "Temporary Legal fees - construction  (incl VAT) Cost to date");
            temporaryLegalFeesConstructionInclVatCostToDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryLegalFeesConstructionInclVatForecast = runtimeEntityType.AddProperty(
                "TemporaryLegalFeesConstructionInclVatForecast",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryLegalFeesConstructionInclVatForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryLegalFeesConstructionInclVatForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryLegalFeesConstructionInclVatForecast.AddAnnotation("Relational:ColumnName", "Temporary Legal fees - construction  (incl VAT) Forecast");
            temporaryLegalFeesConstructionInclVatForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryTaFeesInclVatCostToDate = runtimeEntityType.AddProperty(
                "TemporaryTaFeesInclVatCostToDate",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryTaFeesInclVatCostToDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryTaFeesInclVatCostToDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryTaFeesInclVatCostToDate.AddAnnotation("Relational:ColumnName", "Temporary TA Fees (Incl VAT) Cost to date");
            temporaryTaFeesInclVatCostToDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryTaFeesInclVatForecast = runtimeEntityType.AddProperty(
                "TemporaryTaFeesInclVatForecast",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryTaFeesInclVatForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryTaFeesInclVatForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryTaFeesInclVatForecast.AddAnnotation("Relational:ColumnName", "Temporary TA Fees (Incl VAT) Forecast");
            temporaryTaFeesInclVatForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryTaFeesInclVatForecastComments = runtimeEntityType.AddProperty(
                "TemporaryTaFeesInclVatForecastComments",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryTaFeesInclVatForecastComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryTaFeesInclVatForecastComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryTaFeesInclVatForecastComments.AddAnnotation("Relational:ColumnName", "Temporary TA Fees (Incl VAT) Forecast Comments");
            temporaryTaFeesInclVatForecastComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryTaSurveysInclVatComments = runtimeEntityType.AddProperty(
                "TemporaryTaSurveysInclVatComments",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryTaSurveysInclVatComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryTaSurveysInclVatComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryTaSurveysInclVatComments.AddAnnotation("Relational:ColumnName", "Temporary TA Surveys (Incl VAT) Comments ");
            temporaryTaSurveysInclVatComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryTaSurveysInclVatCostToDate = runtimeEntityType.AddProperty(
                "TemporaryTaSurveysInclVatCostToDate",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryTaSurveysInclVatCostToDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryTaSurveysInclVatCostToDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryTaSurveysInclVatCostToDate.AddAnnotation("Relational:ColumnName", "Temporary TA Surveys (Incl VAT) Cost to date");
            temporaryTaSurveysInclVatCostToDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var temporaryTaSurveysInclVatForecast = runtimeEntityType.AddProperty(
                "TemporaryTaSurveysInclVatForecast",
                typeof(string),
                propertyInfo: typeof(RagtempBudget).GetProperty("TemporaryTaSurveysInclVatForecast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempBudget).GetField("<TemporaryTaSurveysInclVatForecast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            temporaryTaSurveysInclVatForecast.AddAnnotation("Relational:ColumnName", "Temporary TA Surveys (Incl VAT) Forecast");
            temporaryTaSurveysInclVatForecast.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "dbo");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "RAGTEMP_BUDGET");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
