// <auto-generated />
using System;
using System.Reflection;
using Dfe.ManageFreeSchoolProjects.Data.Entities.Existing;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Dfe.ManageFreeSchoolProjects.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class RagtempRatingsEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Dfe.ManageFreeSchoolProjects.Data.Entities.Existing.RagtempRatings",
                typeof(RagtempRatings),
                baseEntityType,
                propertyCount: 11);

            var accidentOnSiteInThisMonthReportedToEfa = runtimeEntityType.AddProperty(
                "AccidentOnSiteInThisMonthReportedToEfa",
                typeof(string),
                propertyInfo: typeof(RagtempRatings).GetProperty("AccidentOnSiteInThisMonthReportedToEfa", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempRatings).GetField("<AccidentOnSiteInThisMonthReportedToEfa>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            accidentOnSiteInThisMonthReportedToEfa.AddAnnotation("Relational:ColumnName", "Accident on site in this month reported to EFA");
            accidentOnSiteInThisMonthReportedToEfa.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fscode = runtimeEntityType.AddProperty(
                "Fscode",
                typeof(string),
                propertyInfo: typeof(RagtempRatings).GetProperty("Fscode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempRatings).GetField("<Fscode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            fscode.AddAnnotation("Relational:ColumnName", "FSCode");
            fscode.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var overallRag = runtimeEntityType.AddProperty(
                "OverallRag",
                typeof(string),
                propertyInfo: typeof(RagtempRatings).GetProperty("OverallRag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempRatings).GetField("<OverallRag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            overallRag.AddAnnotation("Relational:ColumnName", "Overall RAG");
            overallRag.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var taOverallSiteRag = runtimeEntityType.AddProperty(
                "TaOverallSiteRag",
                typeof(string),
                propertyInfo: typeof(RagtempRatings).GetProperty("TaOverallSiteRag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempRatings).GetField("<TaOverallSiteRag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            taOverallSiteRag.AddAnnotation("Relational:ColumnName", "TA Overall Site RAG");
            taOverallSiteRag.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var taOverallSiteRagComments = runtimeEntityType.AddProperty(
                "TaOverallSiteRagComments",
                typeof(string),
                propertyInfo: typeof(RagtempRatings).GetProperty("TaOverallSiteRagComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempRatings).GetField("<TaOverallSiteRagComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            taOverallSiteRagComments.AddAnnotation("Relational:ColumnName", "TA Overall Site RAG Comments");
            taOverallSiteRagComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var taPermanentSiteRag = runtimeEntityType.AddProperty(
                "TaPermanentSiteRag",
                typeof(string),
                propertyInfo: typeof(RagtempRatings).GetProperty("TaPermanentSiteRag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempRatings).GetField("<TaPermanentSiteRag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            taPermanentSiteRag.AddAnnotation("Relational:ColumnName", "TA Permanent Site RAG");
            taPermanentSiteRag.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var taPermanentSiteRagComments = runtimeEntityType.AddProperty(
                "TaPermanentSiteRagComments",
                typeof(string),
                propertyInfo: typeof(RagtempRatings).GetProperty("TaPermanentSiteRagComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempRatings).GetField("<TaPermanentSiteRagComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            taPermanentSiteRagComments.AddAnnotation("Relational:ColumnName", "TA Permanent Site RAG Comments");
            taPermanentSiteRagComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var taSeptemberSiteRag = runtimeEntityType.AddProperty(
                "TaSeptemberSiteRag",
                typeof(string),
                propertyInfo: typeof(RagtempRatings).GetProperty("TaSeptemberSiteRag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempRatings).GetField("<TaSeptemberSiteRag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            taSeptemberSiteRag.AddAnnotation("Relational:ColumnName", "TA September Site RAG");
            taSeptemberSiteRag.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var taSeptemberSiteRagComments = runtimeEntityType.AddProperty(
                "TaSeptemberSiteRagComments",
                typeof(string),
                propertyInfo: typeof(RagtempRatings).GetProperty("TaSeptemberSiteRagComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempRatings).GetField("<TaSeptemberSiteRagComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            taSeptemberSiteRagComments.AddAnnotation("Relational:ColumnName", "TA September Site RAG Comments");
            taSeptemberSiteRagComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var tatemporarySiteRag = runtimeEntityType.AddProperty(
                "TatemporarySiteRag",
                typeof(string),
                propertyInfo: typeof(RagtempRatings).GetProperty("TatemporarySiteRag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempRatings).GetField("<TatemporarySiteRag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            tatemporarySiteRag.AddAnnotation("Relational:ColumnName", "TATemporary Site RAG");
            tatemporarySiteRag.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var tatemporarySiteRagComments = runtimeEntityType.AddProperty(
                "TatemporarySiteRagComments",
                typeof(string),
                propertyInfo: typeof(RagtempRatings).GetProperty("TatemporarySiteRagComments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RagtempRatings).GetField("<TatemporarySiteRagComments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            tatemporarySiteRagComments.AddAnnotation("Relational:ColumnName", "TATemporary Site RAG Comments");
            tatemporarySiteRagComments.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "dbo");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "RAGTEMP_RATINGS");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
