// <auto-generated />
using System;
using System.Reflection;
using Dfe.ManageFreeSchoolProjects.Data.Entities.Existing;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Dfe.ManageFreeSchoolProjects.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class TechnicalQaEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Dfe.ManageFreeSchoolProjects.Data.Entities.Existing.TechnicalQa",
                typeof(TechnicalQa),
                baseEntityType,
                propertyCount: 18);

            var bim = runtimeEntityType.AddProperty(
                "Bim",
                typeof(int),
                propertyInfo: typeof(TechnicalQa).GetProperty("Bim", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TechnicalQa).GetField("<Bim>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            bim.AddAnnotation("Relational:ColumnName", "BIM");
            bim.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var comgdIssued = runtimeEntityType.AddProperty(
                "ComgdIssued",
                typeof(int),
                propertyInfo: typeof(TechnicalQa).GetProperty("ComgdIssued", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TechnicalQa).GetField("<ComgdIssued>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            comgdIssued.AddAnnotation("Relational:ColumnName", "COMGD Issued");
            comgdIssued.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var contractAwardValue = runtimeEntityType.AddProperty(
                "ContractAwardValue",
                typeof(int),
                propertyInfo: typeof(TechnicalQa).GetProperty("ContractAwardValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TechnicalQa).GetField("<ContractAwardValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            contractAwardValue.AddAnnotation("Relational:ColumnName", "Contract Award Value £");
            contractAwardValue.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var contractBudgetValue = runtimeEntityType.AddProperty(
                "ContractBudgetValue",
                typeof(int),
                propertyInfo: typeof(TechnicalQa).GetProperty("ContractBudgetValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TechnicalQa).GetField("<ContractBudgetValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            contractBudgetValue.AddAnnotation("Relational:ColumnName", "Contract Budget Value £");
            contractBudgetValue.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var contractProcurementStatus = runtimeEntityType.AddProperty(
                "ContractProcurementStatus",
                typeof(int),
                propertyInfo: typeof(TechnicalQa).GetProperty("ContractProcurementStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TechnicalQa).GetField("<ContractProcurementStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            contractProcurementStatus.AddAnnotation("Relational:ColumnName", "Contract Procurement Status");
            contractProcurementStatus.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var contractingParty = runtimeEntityType.AddProperty(
                "ContractingParty",
                typeof(int),
                propertyInfo: typeof(TechnicalQa).GetProperty("ContractingParty", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TechnicalQa).GetField("<ContractingParty>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            contractingParty.AddAnnotation("Relational:ColumnName", "Contracting Party");
            contractingParty.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var contractor = runtimeEntityType.AddProperty(
                "Contractor",
                typeof(int),
                propertyInfo: typeof(TechnicalQa).GetProperty("Contractor", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TechnicalQa).GetField("<Contractor>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            contractor.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var deliveryParty = runtimeEntityType.AddProperty(
                "DeliveryParty",
                typeof(int),
                propertyInfo: typeof(TechnicalQa).GetProperty("DeliveryParty", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TechnicalQa).GetField("<DeliveryParty>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            deliveryParty.AddAnnotation("Relational:ColumnName", "Delivery Party");
            deliveryParty.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var enterIntoMainContractActual = runtimeEntityType.AddProperty(
                "EnterIntoMainContractActual",
                typeof(int),
                propertyInfo: typeof(TechnicalQa).GetProperty("EnterIntoMainContractActual", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TechnicalQa).GetField("<EnterIntoMainContractActual>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            enterIntoMainContractActual.AddAnnotation("Relational:ColumnName", "Enter into Main Contract Actual");
            enterIntoMainContractActual.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var feasibilityReportApproved = runtimeEntityType.AddProperty(
                "FeasibilityReportApproved",
                typeof(int),
                propertyInfo: typeof(TechnicalQa).GetProperty("FeasibilityReportApproved", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TechnicalQa).GetField("<FeasibilityReportApproved>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            feasibilityReportApproved.AddAnnotation("Relational:ColumnName", "Feasibility Report Approved");
            feasibilityReportApproved.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var feasibiltyReportStartDate = runtimeEntityType.AddProperty(
                "FeasibiltyReportStartDate",
                typeof(int),
                propertyInfo: typeof(TechnicalQa).GetProperty("FeasibiltyReportStartDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TechnicalQa).GetField("<FeasibiltyReportStartDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            feasibiltyReportStartDate.AddAnnotation("Relational:ColumnName", "Feasibilty Report Start Date");
            feasibiltyReportStartDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var finalContractValue = runtimeEntityType.AddProperty(
                "FinalContractValue",
                typeof(int),
                propertyInfo: typeof(TechnicalQa).GetProperty("FinalContractValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TechnicalQa).GetField("<FinalContractValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            finalContractValue.AddAnnotation("Relational:ColumnName", "Final Contract Value £");
            finalContractValue.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var gifa = runtimeEntityType.AddProperty(
                "Gifa",
                typeof(int),
                propertyInfo: typeof(TechnicalQa).GetProperty("Gifa", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TechnicalQa).GetField("<Gifa>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            gifa.AddAnnotation("Relational:ColumnName", "GIFA");
            gifa.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var month = runtimeEntityType.AddProperty(
                "Month",
                typeof(string),
                propertyInfo: typeof(TechnicalQa).GetProperty("Month", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TechnicalQa).GetField("<Month>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            month.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var pcCertificateIssuedActual = runtimeEntityType.AddProperty(
                "PcCertificateIssuedActual",
                typeof(int),
                propertyInfo: typeof(TechnicalQa).GetProperty("PcCertificateIssuedActual", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TechnicalQa).GetField("<PcCertificateIssuedActual>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            pcCertificateIssuedActual.AddAnnotation("Relational:ColumnName", "PC Certificate Issued Actual");
            pcCertificateIssuedActual.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var procurementRoute = runtimeEntityType.AddProperty(
                "ProcurementRoute",
                typeof(int),
                propertyInfo: typeof(TechnicalQa).GetProperty("ProcurementRoute", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TechnicalQa).GetField("<ProcurementRoute>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            procurementRoute.AddAnnotation("Relational:ColumnName", "Procurement Route");
            procurementRoute.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var procurementStartActual = runtimeEntityType.AddProperty(
                "ProcurementStartActual",
                typeof(int),
                propertyInfo: typeof(TechnicalQa).GetProperty("ProcurementStartActual", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TechnicalQa).GetField("<ProcurementStartActual>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            procurementStartActual.AddAnnotation("Relational:ColumnName", "Procurement Start Actual");
            procurementStartActual.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var typeOfWork = runtimeEntityType.AddProperty(
                "TypeOfWork",
                typeof(int),
                propertyInfo: typeof(TechnicalQa).GetProperty("TypeOfWork", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TechnicalQa).GetField("<TypeOfWork>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            typeOfWork.AddAnnotation("Relational:ColumnName", "Type of Work");
            typeOfWork.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "dbo");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Technical_QA");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
