// <auto-generated />
using System;
using System.Reflection;
using Dfe.ManageFreeSchoolProjects.Data.Entities.Existing;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Dfe.ManageFreeSchoolProjects.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class TermVisitsUtcsEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Dfe.ManageFreeSchoolProjects.Data.Entities.Existing.TermVisitsUtcs",
                typeof(TermVisitsUtcs),
                baseEntityType,
                propertyCount: 12,
                keyCount: 1);

            var rid = runtimeEntityType.AddProperty(
                "Rid",
                typeof(string),
                propertyInfo: typeof(TermVisitsUtcs).GetProperty("Rid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TermVisitsUtcs).GetField("<Rid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 11,
                unicode: false);
            rid.AddAnnotation("Relational:ColumnName", "RID");
            rid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var pRid = runtimeEntityType.AddProperty(
                "PRid",
                typeof(string),
                propertyInfo: typeof(TermVisitsUtcs).GetProperty("PRid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TermVisitsUtcs).GetField("<PRid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 11,
                unicode: false);
            pRid.AddAnnotation("Relational:ColumnName", "p_rid");
            pRid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var periodEnd = runtimeEntityType.AddProperty(
                "PeriodEnd",
                typeof(DateTime),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            periodEnd.AddAnnotation("Relational:ColumnName", "PeriodEnd");
            periodEnd.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var periodStart = runtimeEntityType.AddProperty(
                "PeriodStart",
                typeof(DateTime),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            periodStart.AddAnnotation("Relational:ColumnName", "PeriodStart");
            periodStart.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var termVisitsUtcPostOfstedUtcVisitDateOfVisit = runtimeEntityType.AddProperty(
                "TermVisitsUtcPostOfstedUtcVisitDateOfVisit",
                typeof(DateTime?),
                propertyInfo: typeof(TermVisitsUtcs).GetProperty("TermVisitsUtcPostOfstedUtcVisitDateOfVisit", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TermVisitsUtcs).GetField("<TermVisitsUtcPostOfstedUtcVisitDateOfVisit>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            termVisitsUtcPostOfstedUtcVisitDateOfVisit.AddAnnotation("Relational:ColumnName", "Term Visits UTC.Post-Ofsted UTC Visit: Date of Visit");
            termVisitsUtcPostOfstedUtcVisitDateOfVisit.AddAnnotation("Relational:ColumnType", "date");
            termVisitsUtcPostOfstedUtcVisitDateOfVisit.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var termVisitsUtcPostOfstedUtcVisitNameOfDfEOfficial = runtimeEntityType.AddProperty(
                "TermVisitsUtcPostOfstedUtcVisitNameOfDfEOfficial",
                typeof(string),
                propertyInfo: typeof(TermVisitsUtcs).GetProperty("TermVisitsUtcPostOfstedUtcVisitNameOfDfEOfficial", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TermVisitsUtcs).GetField("<TermVisitsUtcPostOfstedUtcVisitNameOfDfEOfficial>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            termVisitsUtcPostOfstedUtcVisitNameOfDfEOfficial.AddAnnotation("Relational:ColumnName", "Term Visits UTC.Post-Ofsted UTC Visit: Name of DfE official");
            termVisitsUtcPostOfstedUtcVisitNameOfDfEOfficial.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var termVisitsUtcPostOfstedUtcVisitNameOfEducationAdviser = runtimeEntityType.AddProperty(
                "TermVisitsUtcPostOfstedUtcVisitNameOfEducationAdviser",
                typeof(string),
                propertyInfo: typeof(TermVisitsUtcs).GetProperty("TermVisitsUtcPostOfstedUtcVisitNameOfEducationAdviser", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TermVisitsUtcs).GetField("<TermVisitsUtcPostOfstedUtcVisitNameOfEducationAdviser>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            termVisitsUtcPostOfstedUtcVisitNameOfEducationAdviser.AddAnnotation("Relational:ColumnName", "Term Visits UTC.Post-Ofsted UTC Visit: Name of Education Adviser");
            termVisitsUtcPostOfstedUtcVisitNameOfEducationAdviser.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var termVisitsUtcPostOfstedUtcVisitNextVisitDate = runtimeEntityType.AddProperty(
                "TermVisitsUtcPostOfstedUtcVisitNextVisitDate",
                typeof(DateTime?),
                propertyInfo: typeof(TermVisitsUtcs).GetProperty("TermVisitsUtcPostOfstedUtcVisitNextVisitDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TermVisitsUtcs).GetField("<TermVisitsUtcPostOfstedUtcVisitNextVisitDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            termVisitsUtcPostOfstedUtcVisitNextVisitDate.AddAnnotation("Relational:ColumnName", "Term Visits UTC.Post-Ofsted UTC Visit: Next visit date");
            termVisitsUtcPostOfstedUtcVisitNextVisitDate.AddAnnotation("Relational:ColumnType", "date");
            termVisitsUtcPostOfstedUtcVisitNextVisitDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var termVisitsUtcPostOfstedUtcVisitReportLink = runtimeEntityType.AddProperty(
                "TermVisitsUtcPostOfstedUtcVisitReportLink",
                typeof(string),
                propertyInfo: typeof(TermVisitsUtcs).GetProperty("TermVisitsUtcPostOfstedUtcVisitReportLink", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TermVisitsUtcs).GetField("<TermVisitsUtcPostOfstedUtcVisitReportLink>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            termVisitsUtcPostOfstedUtcVisitReportLink.AddAnnotation("Relational:ColumnName", "Term Visits UTC.Post-Ofsted UTC Visit: Report link");
            termVisitsUtcPostOfstedUtcVisitReportLink.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var termVisitsUtcPostOfstedUtcVisitSummary = runtimeEntityType.AddProperty(
                "TermVisitsUtcPostOfstedUtcVisitSummary",
                typeof(string),
                propertyInfo: typeof(TermVisitsUtcs).GetProperty("TermVisitsUtcPostOfstedUtcVisitSummary", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TermVisitsUtcs).GetField("<TermVisitsUtcPostOfstedUtcVisitSummary>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                unicode: false);
            termVisitsUtcPostOfstedUtcVisitSummary.AddAnnotation("Relational:ColumnName", "Term Visits UTC.Post-Ofsted UTC Visit: Summary");
            termVisitsUtcPostOfstedUtcVisitSummary.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var termVisitsUtcPostOfstedUtcVisitVisitRating = runtimeEntityType.AddProperty(
                "TermVisitsUtcPostOfstedUtcVisitVisitRating",
                typeof(string),
                propertyInfo: typeof(TermVisitsUtcs).GetProperty("TermVisitsUtcPostOfstedUtcVisitVisitRating", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TermVisitsUtcs).GetField("<TermVisitsUtcPostOfstedUtcVisitVisitRating>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            termVisitsUtcPostOfstedUtcVisitVisitRating.AddAnnotation("Relational:ColumnName", "Term Visits UTC.Post-Ofsted UTC Visit: Visit Rating");
            termVisitsUtcPostOfstedUtcVisitVisitRating.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var termVisitsUtcSchoolTermVisit = runtimeEntityType.AddProperty(
                "TermVisitsUtcSchoolTermVisit",
                typeof(string),
                propertyInfo: typeof(TermVisitsUtcs).GetProperty("TermVisitsUtcSchoolTermVisit", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TermVisitsUtcs).GetField("<TermVisitsUtcSchoolTermVisit>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            termVisitsUtcSchoolTermVisit.AddAnnotation("Relational:ColumnName", "Term Visits UTC.School term Visit");
            termVisitsUtcSchoolTermVisit.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { rid });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "dbo");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Term_Visits_UTCs");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);
            runtimeEntityType.AddAnnotation("SqlServer:IsTemporal", true);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
