// <auto-generated />
using System;
using System.Reflection;
using Dfe.ManageFreeSchoolProjects.Data.Entities.Existing;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Dfe.ManageFreeSchoolProjects.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class TrustEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Dfe.ManageFreeSchoolProjects.Data.Entities.Existing.Trust",
                typeof(Trust),
                baseEntityType,
                propertyCount: 11,
                keyCount: 1);

            var rid = runtimeEntityType.AddProperty(
                "Rid",
                typeof(string),
                propertyInfo: typeof(Trust).GetProperty("Rid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Trust).GetField("<Rid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 11,
                unicode: false);
            rid.AddAnnotation("Relational:ColumnName", "RID");
            rid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var leadSponsor = runtimeEntityType.AddProperty(
                "LeadSponsor",
                typeof(string),
                propertyInfo: typeof(Trust).GetProperty("LeadSponsor", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Trust).GetField("<LeadSponsor>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 7,
                unicode: false);
            leadSponsor.AddAnnotation("Relational:ColumnName", "Lead Sponsor");
            leadSponsor.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var pRid = runtimeEntityType.AddProperty(
                "PRid",
                typeof(string),
                propertyInfo: typeof(Trust).GetProperty("PRid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Trust).GetField("<PRid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 11,
                unicode: false);
            pRid.AddAnnotation("Relational:ColumnName", "p_rid");
            pRid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var periodEnd = runtimeEntityType.AddProperty(
                "PeriodEnd",
                typeof(DateTime),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            periodEnd.AddAnnotation("Relational:ColumnName", "PeriodEnd");
            periodEnd.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var periodStart = runtimeEntityType.AddProperty(
                "PeriodStart",
                typeof(DateTime),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            periodStart.AddAnnotation("Relational:ColumnName", "PeriodStart");
            periodStart.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var trustRef = runtimeEntityType.AddProperty(
                "TrustRef",
                typeof(string),
                propertyInfo: typeof(Trust).GetProperty("TrustRef", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Trust).GetField("<TrustRef>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 7,
                unicode: false);
            trustRef.AddAnnotation("Relational:ColumnName", "Trust ref");
            trustRef.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var trustsLeadSponsorId = runtimeEntityType.AddProperty(
                "TrustsLeadSponsorId",
                typeof(string),
                propertyInfo: typeof(Trust).GetProperty("TrustsLeadSponsorId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Trust).GetField("<TrustsLeadSponsorId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 5,
                unicode: false);
            trustsLeadSponsorId.AddAnnotation("Relational:ColumnName", "Trusts.Lead sponsor id");
            trustsLeadSponsorId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var trustsLeadSponsorName = runtimeEntityType.AddProperty(
                "TrustsLeadSponsorName",
                typeof(string),
                propertyInfo: typeof(Trust).GetProperty("TrustsLeadSponsorName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Trust).GetField("<TrustsLeadSponsorName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            trustsLeadSponsorName.AddAnnotation("Relational:ColumnName", "Trusts.Lead sponsor name");
            trustsLeadSponsorName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var trustsTrustName = runtimeEntityType.AddProperty(
                "TrustsTrustName",
                typeof(string),
                propertyInfo: typeof(Trust).GetProperty("TrustsTrustName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Trust).GetField("<TrustsTrustName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            trustsTrustName.AddAnnotation("Relational:ColumnName", "Trusts.Trust name");
            trustsTrustName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var trustsTrustRef = runtimeEntityType.AddProperty(
                "TrustsTrustRef",
                typeof(string),
                propertyInfo: typeof(Trust).GetProperty("TrustsTrustRef", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Trust).GetField("<TrustsTrustRef>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 5,
                unicode: false);
            trustsTrustRef.AddAnnotation("Relational:ColumnName", "Trusts.Trust ref");
            trustsTrustRef.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var trustsTrustType = runtimeEntityType.AddProperty(
                "TrustsTrustType",
                typeof(string),
                propertyInfo: typeof(Trust).GetProperty("TrustsTrustType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Trust).GetField("<TrustsTrustType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            trustsTrustType.AddAnnotation("Relational:ColumnName", "Trusts.Trust type");
            trustsTrustType.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { rid });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "dbo");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Trust");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);
            runtimeEntityType.AddAnnotation("SqlServer:IsTemporal", true);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
